In [1]:
import pandas as pd

# github 에 수정해서 올려보자

In [1]:
print('a')

a

In [31]:
data = pd.read_csv('train.csv')

In [3]:
data.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

PassengerId       0
HomePlanet      201 - 흠..
CryoSleep       217 - 흠2..
Cabin           199 - 분류해보자 A,B - F 로 보단 S / P 로 분류하는게 더 나을거 같은데?!
Destination     182 - 최빈값 넣자
Age             179 - 연령대로 분류하자.
VIP             203 - 
RoomService     181 - TotalCost
FoodCourt       183 - TotalCost
ShoppingMall    208 - TotalCost
Spa             183 - TotalCost
VRDeck          188 - TotalCost
Name            200 - 안중요 날려
Transported       0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [5]:
data_drop = data.dropna()

In [6]:
data_drop.shape

(6606, 14)

In [7]:
data.shape

(8693, 14)

In [ ]:
for i in data.columns[1:] :
    print(i)
    print(data[i].unique())
    print(data[i].value_counts())
    print(data[i].isnull().sum())
    print('---의 True수')
    print(data.groupby(i)['Transported'].sum())
    print('---')

In [10]:
data_cost = data[['RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']].fillna(0)

In [9]:
data['RoomService'].isnull().sum()

181

In [11]:
data_cost['Total_cost'] = data_cost['RoomService'] + data_cost['FoodCourt'] + data_cost['ShoppingMall'] + data_cost['Spa'] + data_cost['VRDeck']

In [12]:
data['Total_cost'] = data_cost['Total_cost']

In [13]:
data['Total_cost'].isnull().sum()

0

In [14]:
dic_id = {}
for i in data['PassengerId'] :
    dic_id[i] = i[:4]

In [15]:
dic_id

{'0001_01': '0001',
 '0002_01': '0002',
 '0003_01': '0003',
 '0003_02': '0003',
 '0004_01': '0004',
 '0005_01': '0005',
 '0006_01': '0006',
 '0006_02': '0006',
 '0007_01': '0007',
 '0008_01': '0008',
 '0008_02': '0008',
 '0008_03': '0008',
 '0009_01': '0009',
 '0010_01': '0010',
 '0011_01': '0011',
 '0012_01': '0012',
 '0014_01': '0014',
 '0015_01': '0015',
 '0016_01': '0016',
 '0017_01': '0017',
 '0017_02': '0017',
 '0020_01': '0020',
 '0020_02': '0020',
 '0020_03': '0020',
 '0020_04': '0020',
 '0020_05': '0020',
 '0020_06': '0020',
 '0022_01': '0022',
 '0024_01': '0024',
 '0025_01': '0025',
 '0026_01': '0026',
 '0028_01': '0028',
 '0030_01': '0030',
 '0031_01': '0031',
 '0031_02': '0031',
 '0031_03': '0031',
 '0034_01': '0034',
 '0035_01': '0035',
 '0036_01': '0036',
 '0038_01': '0038',
 '0039_01': '0039',
 '0041_01': '0041',
 '0043_01': '0043',
 '0044_01': '0044',
 '0044_02': '0044',
 '0044_03': '0044',
 '0045_01': '0045',
 '0045_02': '0045',
 '0050_01': '0050',
 '0051_01': '0051',
 '0052_01': '0052',
 '0053_01': '0053',
 '0056_01': '0056',
 '0056_02': '0056',
 '0056_03': '0056',
 '0058_01': '0058',
 '0061_01': '0061',
 '0062_01': '0062',
 '0064_01': '0064',
 '0064_02': '0064',
 '0066_01': '0066',
 '0067_01': '0067',
 '0067_02': '0067',
 '0067_03': '0067',
 '0068_01': '0068',
 '0069_01': '0069',
 '0070_01': '0070',
 '0071_01': '0071',
 '0072_01': '0072',
 '0073_01': '0073',
 '0074_01': '0074',
 '0076_01': '0076',
 '0077_01': '0077',
 '0078_01': '0078',
 '0081_01': '0081',
 '0082_01': '0082',
 '0082_02': '0082',
 '0082_03': '0082',
 '0084_01': '0084',
 '0085_01': '0085',
 '0086_01': '0086',
 '0088_01': '0088',
 '0090_01': '0090',
 '0091_01': '0091',
 '0091_02': '0091',
 '0092_01': '0092',
 '0092_02': '0092',
 '0092_03': '0092',
 '0097_01': '0097',
 '0098_01': '0098',
 '0098_02': '0098',
 '0099_01': '0099',
 '0099_02': '0099',
 '0101_01': '0101',
 '0102_01': '0102',
 '0103_01': '0103',
 '0103_02': '0103',
 '0103_03': '0103',
 '0105_01': '0105',
 '0107_01': '0107',
 '0108_01': '0108',
 '0108_02': '0108',
 '0108_03': '0108',
 '0110_01': '0110',
 '0110_02': '0110',
 '0110_03': '0110',
 '0110_04': '0110',
 '0111_01': '0111',
 '0112_01': '0112',
 '0113_01': '0113',
 '0114_01': '0114',
 '0115_01': '0115',
 '0116_01': '0116',
 '0119_01': '0119',
 '0119_02': '0119',
 '0120_01': '0120',
 '0122_01': '0122',
 '0123_01': '0123',
 '0126_01': '0126',
 '0127_01': '0127',
 '0128_01': '0128',
 '0128_02': '0128',
 '0129_01': '0129',
 '0133_01': '0133',
 '0133_02': '0133',
 '0134_01': '0134',
 '0136_01': '0136',
 '0138_01': '0138',
 '0138_02': '0138',
 '0139_01': '0139',
 '0140_01': '0140',
 '0140_02': '0140',
 '0141_01': '0141',
 '0144_01': '0144',
 '0146_01': '0146',
 '0147_01': '0147',
 '0148_01': '0148',
 '0149_01': '0149',
 '0151_01': '0151',
 '0152_01': '0152',
 '0160_01': '0160',
 '0163_01': '0163',
 '0163_02': '0163',
 '0164_01': '0164',
 '0164_02': '0164',
 '0165_01': '0165',
 '0167_01': '0167',
 '0167_02': '0167',
 '0169_01': '0169',
 '0170_01': '0170',
 '0171_01': '0171',
 '0172_01': '0172',
 '0173_01': '0173',
 '0174_01': '0174',
 '0177_01': '0177',
 '0178_01': '0178',
 '0179_01': '0179',
 '0179_02': '0179',
 '0179_03': '0179',
 '0181_01': '0181',
 '0182_01': '0182',
 '0183_01': '0183',
 '0186_01': '0186',
 '0188_01': '0188',
 '0189_01': '0189',
 '0190_01': '0190',
 '0192_01': '0192',
 '0192_02': '0192',
 '0192_03': '0192',
 '0193_01': '0193',
 '0193_02': '0193',
 '0193_03': '0193',
 '0195_01': '0195',
 '0196_01': '0196',
 '0197_01': '0197',
 '0198_01': '0198',
 '0199_01': '0199',
 '0200_01': '0200',
 '0201_01': '0201',
 '0201_02': '0201',
 '0202_01': '0202',
 '0202_02': '0202',
 '0203_01': '0203',
 '0205_01': '0205',
 '0206_01': '0206',
 '0207_01': '0207',
 '0210_01': '0210',
 '0211_01': '0211',
 '0211_02': '0211',
 '0211_03': '0211',
 '0212_01': '0212',
 '0212_02': '0212',
 '0213_01': '0213',
 '0216_01': '0216',
 '0217_01': '0217',
 '0219_01': '0219',
 '0220_01': '0220',
 '0220_02': '0220',
 '0220_03': '0220',
 '0220_04': '0220',
 '0220_05': '0220',
 '0220_06': '0220',
 '0220_07': '0220',
 '0221_01': '0221',
 '0221_02': '0221',
 '0221_03': '0221',
 '0221_04': '0221',
 '0221_05': '0221',
 '0221_06': '0221',
 '0221_07': '0221',
 '0222_01': '0222',
 '0222_02': '0222',
 '0222_03': '0222',
 '0223_01': '0223',
 '0224_01': '0224',
 '0225_01': '0225',
 '0229_01': '0229',
 '0231_01': '0231',
 '0232_01': '0232',
 '0233_01': '0233',
 '0234_01': '0234',
 '0237_01': '0237',
 '0239_01': '0239',
 '0240_01': '0240',
 '0241_01': '0241',
 '0242_01': '0242',
 '0243_01': '0243',
 '0244_01': '0244',
 '0244_02': '0244',
 '0245_01': '0245',
 '0245_02': '0245',
 '0246_01': '0246',
 '0248_01': '0248',
 '0250_01': '0250',
 '0251_01': '0251',
 '0252_01': '0252',
 '0253_01': '0253',
 '0254_01': '0254',
 '0255_01': '0255',
 '0257_01': '0257',
 '0257_02': '0257',
 '0258_01': '0258',
 '0260_01': '0260',
 '0261_01': '0261',
 '0263_01': '0263',
 '0265_01': '0265',
 '0267_01': '0267',
 '0269_01': '0269',
 '0270_01': '0270',
 '0275_01': '0275',
 '0277_01': '0277',
 '0278_01': '0278',
 '0278_02': '0278',
 '0281_01': '0281',
 '0282_01': '0282',
 '0283_01': '0283',
 '0283_02': '0283',
 '0285_01': '0285',
 '0285_02': '0285',
 '0286_01': '0286',
 '0287_01': '0287',
 '0287_02': '0287',
 '0288_01': '0288',
 '0289_01': '0289',
 '0290_01': '0290',
 '0290_02': '0290',
 '0290_03': '0290',
 '0290_04': '0290',
 '0291_01': '0291',
 '0294_01': '0294',
 '0297_01': '0297',
 '0298_01': '0298',
 '0301_01': '0301',
 '0302_01': '0302',
 '0303_01': '0303',
 '0304_01': '0304',
 '0305_01': '0305',
 '0306_01': '0306',
 '0307_01': '0307',
 '0309_01': '0309',
 '0310_01': '0310',
 '0313_01': '0313',
 '0313_02': '0313',
 '0313_03': '0313',
 '0313_04': '0313',
 '0314_01': '0314',
 '0315_01': '0315',
 '0316_01': '0316',
 '0316_02': '0316',
 '0320_01': '0320',
 '0320_02': '0320',
 '0321_01': '0321',
 '0322_01': '0322',
 '0324_01': '0324',
 '0326_01': '0326',
 '0327_01': '0327',
 '0330_01': '0330',
 '0330_02': '0330',
 '0330_03': '0330',
 '0331_01': '0331',
 '0333_01': '0333',
 '0334_01': '0334',
 '0336_01': '0336',
 '0337_01': '0337',
 '0337_02': '0337',
 '0337_03': '0337',
 '0338_01': '0338',
 '0340_01': '0340',
 '0341_01': '0341',
 '0343_01': '0343',
 '0345_01': '0345',
 '0346_01': '0346',
 '0347_01': '0347',
 '0348_01': '0348',
 '0348_02': '0348',
 '0350_01': '0350',
 '0352_01': '0352',
 '0355_01': '0355',
 '0356_01': '0356',
 '0357_01': '0357',
 '0358_01': '0358',
 '0358_02': '0358',
 '0359_01': '0359',
 '0360_01': '0360',
 '0361_01': '0361',
 '0365_01': '0365',
 '0368_01': '0368',
 '0368_02': '0368',
 '0369_01': '0369',
 '0370_01': '0370',
 '0371_01': '0371',
 '0372_01': '0372',
 '0373_01': '0373',
 '0375_01': '0375',
 '0376_01': '0376',
 '0377_01': '0377',
 '0378_01': '0378',
 '0378_02': '0378',
 '0378_03': '0378',
 '0378_04': '0378',
 '0378_05': '0378',
 '0378_06': '0378',
 '0378_07': '0378',
 '0379_01': '0379',
 '0380_01': '0380',
 '0381_01': '0381',
 '0381_02': '0381',
 '0382_01': '0382',
 '0383_01': '0383',
 '0383_02': '0383',
 '0384_01': '0384',
 '0384_02': '0384',
 '0385_01': '0385',
 '0387_01': '0387',
 '0388_01': '0388',
 '0389_01': '0389',
 '0391_01': '0391',
 '0392_01': '0392',
 '0395_01': '0395',
 '0395_02': '0395',
 '0396_01': '0396',
 '0397_01': '0397',
 '0398_01': '0398',
 '0401_01': '0401',
 '0401_02': '0401',
 '0402_01': '0402',
 '0403_01': '0403',
 '0405_01': '0405',
 '0407_01': '0407',
 '0407_02': '0407',
 '0407_03': '0407',
 '0408_01': '0408',
 '0409_01': '0409',
 '0410_01': '0410',
 '0411_01': '0411',
 '0412_01': '0412',
 '0413_01': '0413',
 '0415_01': '0415',
 '0417_01': '0417',
 '0417_02': '0417',
 '0417_03': '0417',
 '0423_01': '0423',
 '0425_01': '0425',
 '0425_02': '0425',
 '0425_03': '0425',
 '0427_01': '0427',
 '0428_01': '0428',
 '0429_01': '0429',
 '0429_02': '0429',
 '0430_01': '0430',
 '0431_01': '0431',
 '0432_01': '0432',
 '0433_01': '0433',
 '0433_02': '0433',
 '0434_01': '0434',
 '0435_01': '0435',
 '0436_01': '0436',
 '0436_02': '0436',
 '0437_01': '0437',
 '0437_02': '0437',
 '0438_01': '0438',
 '0439_01': '0439',
 '0441_01': '0441',
 '0442_01': '0442',
 '0444_01': '0444',
 '0444_02': '0444',
 '0445_01': '0445',
 '0445_02': '0445',
 '0446_01': '0446',
 '0447_01': '0447',
 '0448_01': '0448',
 '0448_02': '0448',
 '0449_01': '0449',
 '0452_01': '0452',
 '0453_01': '0453',
 '0453_02': '0453',
 '0453_03': '0453',
 '0454_01': '0454',
 '0454_02': '0454',
 '0454_03': '0454',
 '0456_01': '0456',
 '0457_01': '0457',
 '0457_02': '0457',
 '0457_03': '0457',
 '0458_01': '0458',
 '0459_01': '0459',
 '0460_01': '0460',
 '0461_01': '0461',
 '0461_02': '0461',
 '0461_03': '0461',
 '0462_01': '0462',
 '0463_01': '0463',
 '0463_02': '0463',
 '0465_01': '0465',
 '0465_02': '0465',
 '0466_01': '0466',
 '0468_01': '0468',
 '0470_01': '0470',
 '0470_02': '0470',
 '0471_01': '0471',
 '0471_02': '0471',
 '0472_01': '0472',
 '0474_01': '0474',
 '0475_01': '0475',
 '0476_01': '0476',
 '0476_02': '0476',
 '0476_03': '0476',
 '0477_01': '0477',
 '0480_01': '0480',
 '0481_01': '0481',
 '0482_01': '0482',
 '0482_02': '0482',
 '0485_01': '0485',
 '0487_01': '0487',
 '0488_01': '0488',
 '0490_01': '0490',
 '0498_01': '0498',
 '0498_02': '0498',
 '0499_01': '0499',
 '0499_02': '0499',
 '0500_01': '0500',
 '0501_01': '0501',
 '0502_01': '0502',
 '0503_01': '0503',
 '0503_02': '0503',
 '0503_03': '0503',
 '0504_01': '0504',
 '0504_02': '0504',
 '0504_03': '0504',
 '0504_04': '0504',
 '0504_05': '0504',
 '0504_06': '0504',
 '0506_01': '0506',
 '0507_01': '0507',
 '0510_01': '0510',
 '0512_01': '0512',
 '0512_02': '0512',
 '0513_01': '0513',
 '0515_01': '0515',
 '0516_01': '0516',
 '0517_01': '0517',
 '0518_01': '0518',
 '0519_01': '0519',
 '0520_01': '0520',
 '0521_01': '0521',
 '0522_01': '0522',
 '0523_01': '0523',
 '0525_01': '0525',
 '0527_01': '0527',
 '0527_02': '0527',
 '0528_01': '0528',
 '0529_01': '0529',
 '0531_01': '0531',
 '0531_02': '0531',
 '0533_01': '0533',
 '0534_01': '0534',
 '0534_02': '0534',
 '0537_01': '0537',
 '0538_01': '0538',
 '0539_01': '0539',
 '0539_02': '0539',
 '0539_03': '0539',
 '0539_04': '0539',
 '0539_05': '0539',
 '0540_01': '0540',
 '0540_02': '0540',
 '0542_01': '0542',
 '0545_01': '0545',
 '0546_01': '0546',
 '0547_01': '0547',
 '0548_01': '0548',
 '0549_01': '0549',
 '0549_02': '0549',
 '0550_01': '0550',
 '0551_01': '0551',
 '0552_01': '0552',
 '0553_01': '0553',
 '0553_02': '0553',
 '0555_01': '0555',
 '0555_02': '0555',
 '0556_01': '0556',
 '0559_01': '0559',
 '0560_01': '0560',
 '0560_02': '0560',
 '0560_03': '0560',
 '0561_01': '0561',
 '0563_01': '0563',
 '0564_01': '0564',
 '0564_02': '0564',
 '0564_03': '0564',
 '0565_01': '0565',
 '0566_01': '0566',
 '0567_01': '0567',
 '0568_01': '0568',
 '0568_02': '0568',
 '0569_01': '0569',
 '0570_01': '0570',
 '0571_01': '0571',
 '0571_02': '0571',
 '0571_03': '0571',
 '0571_04': '0571',
 '0571_05': '0571',
 '0571_06': '0571',
 '0571_07': '0571',
 '0572_01': '0572',
 '0573_01': '0573',
 '0575_01': '0575',
 '0576_01': '0576',
 '0577_01': '0577',
 '0579_01': '0579',
 '0579_02': '0579',
 '0580_01': '0580',
 '0581_01': '0581',
 '0582_01': '0582',
 '0583_01': '0583',
 '0583_02': '0583',
 '0583_03': '0583',
 '0585_01': '0585',
 '0585_02': '0585',
 '0585_03': '0585',
 '0586_01': '0586',
 '0587_01': '0587',
 '0588_01': '0588',
 '0589_01': '0589',
 '0590_01': '0590',
 '0591_01': '0591',
 '0593_01': '0593',
 '0594_01': '0594',
 '0594_02': '0594',
 '0596_01': '0596',
 '0597_01': '0597',
 '0597_02': '0597',
 '0598_01': '0598',
 '0599_01': '0599',
 '0599_02': '0599',
 '0599_03': '0599',
 '0599_04': '0599',
 '0600_01': '0600',
 '0602_01': '0602',
 '0602_02': '0602',
 '0602_03': '0602',
 '0603_01': '0603',
 '0607_01': '0607',
 '0607_02': '0607',
 '0607_03': '0607',
 '0608_01': '0608',
 '0609_01': '0609',
 '0610_01': '0610',
 '0611_01': '0611',
 '0612_01': '0612',
 '0614_01': '0614',
 '0615_01': '0615',
 '0615_02': '0615',
 '0615_03': '0615',
 '0618_01': '0618',
 '0618_02': '0618',
 '0619_01': '0619',
 '0619_02': '0619',
 '0623_01': '0623',
 '0628_01': '0628',
 '0629_01': '0629',
 '0630_01': '0630',
 '0631_01': '0631',
 '0633_01': '0633',
 '0634_01': '0634',
 '0635_01': '0635',
 '0635_02': '0635',
 '0636_01': '0636',
 '0636_02': '0636',
 '0637_01': '0637',
 '0638_01': '0638',
 '0639_01': '0639',
 '0641_01': '0641',
 '0642_01': '0642',
 '0642_02': '0642',
 '0642_03': '0642',
 '0642_04': '0642',
 '0642_05': '0642',
 '0643_01': '0643',
 '0644_01': '0644',
 '0645_01': '0645',
 '0646_01': '0646',
 '0647_01': '0647',
 '0647_02': '0647',
 '0647_03': '0647',
 '0650_01': '0650',
 '0653_01': '0653',
 '0655_01': '0655',
 '0656_01': '0656',
 '0657_01': '0657',
 '0657_02': '0657',
 '0658_01': '0658',
 '0659_01': '0659',
 '0660_01': '0660',
 '0661_01': '0661',
 '0663_01': '0663',
 '0664_01': '0664',
 '0665_01': '0665',
 '0665_02': '0665',
 '0668_01': '0668',
 '0669_01': '0669',
 '0671_01': '0671',
 '0672_01': '0672',
 '0674_01': '0674',
 '0677_01': '0677',
 '0678_01': '0678',
 '0679_01': '0679',
 '0680_01': '0680',
 '0680_02': '0680',
 '0680_03': '0680',
 '0682_01': '0682',
 '0683_01': '0683',
 '0684_01': '0684',
 '0684_02': '0684',
 '0684_03': '0684',
 '0685_01': '0685',
 '0686_01': '0686',
 '0686_02': '0686',
 '0687_01': '0687',
 '0688_01': '0688',
 '0689_01': '0689',
 '0690_01': '0690',
 '0691_01': '0691',
 '0691_02': '0691',
 '0691_03': '0691',
 '0693_01': '0693',
 '0693_02': '0693',
 '0696_01': '0696',
 '0697_01': '0697',
 '0699_01': '0699',
 '0699_02': '0699',
 '0701_01': '0701',
 '0702_01': '0702',
 '0703_01': '0703',
 '0704_01': '0704',
 '0705_01': '0705',
 '0707_01': '0707',
 '0709_01': '0709',
 '0709_02': '0709',
 '0709_03': '0709',
 '0710_01': '0710',
 '0712_01': '0712',
 '0712_02': '0712',
 '0713_01': '0713',
 '0714_01': '0714',
 '0714_02': '0714',
 '0714_03': '0714',
 '0714_04': '0714',
 '0714_05': '0714',
 '0714_06': '0714',
 '0714_07': '0714',
 '0715_01': '0715',
 '0718_01': '0718',
 '0719_01': '0719',
 '0724_01': '0724',
 '0726_01': '0726',
 '0727_01': '0727',
 '0728_01': '0728',
 '0729_01': '0729',
 '0732_01': '0732',
 '0733_01': '0733',
 '0734_01': '0734',
 '0736_01': '0736',
 '0737_01': '0737',
 '0738_01': '0738',
 '0740_01': '0740',
 '0740_02': '0740',
 '0740_03': '0740',
 '0743_01': '0743',
 '0746_01': '0746',
 '0750_01': '0750',
 '0753_01': '0753',
 '0753_02': '0753',
 '0753_03': '0753',
 '0754_01': '0754',
 '0756_01': '0756',
 '0756_02': '0756',
 '0756_03': '0756',
 '0757_01': '0757',
 '0761_01': '0761',
 '0762_01': '0762',
 '0764_01': '0764',
 '0765_01': '0765',
 '0765_02': '0765',
 '0767_01': '0767',
 '0768_01': '0768',
 '0768_02': '0768',
 '0769_01': '0769',
 '0770_01': '0770',
 '0770_02': '0770',
 '0770_03': '0770',
 '0770_04': '0770',
 '0770_05': '0770',
 '0770_06': '0770',
 '0771_01': '0771',
 '0772_01': '0772',
 '0772_02': '0772',
 '0772_03': '0772',
 '0772_04': '0772',
 '0773_01': '0773',
 '0776_01': '0776',
 '0777_01': '0777',
 '0779_01': '0779',
 '0781_01': '0781',
 '0782_01': '0782',
 '0784_01': '0784',
 '0785_01': '0785',
 '0786_01': '0786',
 '0787_01': '0787',
 '0788_01': '0788',
 '0789_01': '0789',
 '0789_02': '0789',
 '0789_03': '0789',
 '0790_01': '0790',
 '0791_01': '0791',
 '0793_01': '0793',
 '0794_01': '0794',
 '0794_02': '0794',
 '0795_01': '0795',
 '0796_01': '0796',
 '0797_01': '0797',
 '0798_01': '0798',
 '0799_01': '0799',
 '0802_01': '0802',
 '0805_01': '0805',
 '0806_01': '0806',
 '0806_02': '0806',
 '0808_01': '0808',
 '0809_01': '0809',
 '0809_02': '0809',
 '0809_03': '0809',
 '0809_04': '0809',
 '0811_01': '0811',
 '0811_02': '0811',
 '0811_03': '0811',
 '0813_01': '0813',
 '0815_01': '0815',
 '0816_01': '0816',
 '0817_01': '0817',
 '0818_01': '0818',
 '0819_01': '0819',
 '0820_01': '0820',
 '0820_02': '0820',
 '0822_01': '0822',
 '0823_01': '0823',
 '0823_02': '0823',
 '0824_01': '0824',
 '0825_01': '0825',
 '0826_01': '0826',
 '0828_01': '0828',
 '0828_02': '0828',
 '0829_01': '0829',
 '0830_01': '0830',
 '0833_01': '0833',
 '0834_01': '0834',
 '0835_01': '0835',
 '0836_01': '0836',
 '0839_01': '0839',
 '0840_01': '0840',
 '0845_01': '0845',
 '0846_01': '0846',
 '0848_01': '0848',
 '0848_02': '0848',
 '0849_01': '0849',
 '0849_02': '0849',
 '0850_01': '0850',
 '0851_01': '0851',
 '0853_01': '0853',
 '0859_01': '0859',
 '0860_01': '0860',
 '0863_01': '0863',
 '0863_02': '0863',
 '0863_03': '0863',
 '0865_01': '0865',
 '0865_02': '0865',
 '0867_01': '0867',
 '0868_01': '0868',
 '0869_01': '0869',
 '0870_01': '0870',
 '0871_01': '0871',
 '0873_01': '0873',
 '0874_01': '0874',
 '0875_01': '0875',
 '0876_01': '0876',
 '0877_01': '0877',
 '0878_01': '0878',
 '0879_01': '0879',
 '0881_01': '0881',
 '0883_01': '0883',
 '0885_01': '0885',
 '0885_02': '0885',
 '0889_01': '0889',
 '0889_02': '0889',
 '0890_01': '0890',
 '0893_01': '0893',
 '0898_01': '0898',
 '0899_01': '0899',
 '0899_02': '0899',
 '0901_01': '0901',
 '0902_01': '0902',
 '0903_01': '0903',
 '0904_01': '0904',
 '0905_01': '0905',
 '0906_01': '0906',
 '0907_01': '0907',
 '0907_02': '0907',
 '0910_01': '0910',
 '0911_01': '0911',
 '0911_02': '0911',
 '0912_01': '0912',
 '0913_01': '0913',
 '0915_01': '0915',
 '0918_01': '0918',
 '0919_01': '0919',
 '0921_01': '0921',
 '0922_01': '0922',
 '0922_02': '0922',
 '0923_01': '0923',
 '0923_02': '0923',
 '0924_01': '0924',
 '0925_01': '0925',
 '0925_02': '0925',
 '0925_03': '0925',
 '0926_01': '0926',
 '0926_02': '0926',
 '0927_01': '0927',
 '0928_01': '0928',
 '0930_01': '0930',
 '0930_02': '0930',
 '0931_01': '0931',
 '0932_01': '0932',
 '0933_01': '0933',
 '0933_02': '0933',
 '0935_01': '0935',
 '0938_01': '0938',
 '0938_02': '0938',
 '0938_03': '0938',
 '0939_01': '0939',
 '0940_01': '0940',
 '0941_01': '0941',
 '0942_01': '0942',
 '0944_01': '0944',
 '0944_02': '0944',
 '0946_01': '0946',
 '0947_01': '0947',
 '0949_01': '0949',
 '0951_01': '0951',
 '0952_01': '0952',
 '0953_01': '0953',
 '0955_01': '0955',
 '0956_01': '0956',
 '0957_01': '0957',
 '0960_01': '0960',
 '0961_01': '0961',
 '0964_01': '0964',
 '0964_02': '0964',
 '0965_01': '0965',
 '0966_01': '0966',
 '0968_01': '0968',
 '0969_01': '0969',
 '0970_01': '0970',
 '0971_01': '0971',
 '0972_01': '0972',
 '0975_01': '0975',
 '0976_01': '0976',
 '0978_01': '0978',
 '0979_01': '0979',
 '0982_01': '0982',
 '0982_02': '0982',
 '0983_01': '0983',
 '0984_01': '0984',
 '0984_02': '0984',
 '0984_03': '0984',
 '0984_04': '0984',
 '0984_05': '0984',
 '0984_06': '0984',
 '0984_07': '0984',
 '0984_08': '0984',
 '0985_01': '0985',
 '0987_01': '0987',
 '0988_01': '0988',
 '0988_02': '0988',
 '0989_01': '0989',
 '0990_01': '0990',
 '0991_01': '0991',
 '0992_01': '0992',
 '0992_02': '0992',
 '0992_03': '0992',
 '0992_04': '0992',
 '0992_05': '0992',
 '0992_06': '0992',
 '0993_01': '0993',
 '0994_01': '0994',
 '0994_02': '0994',
 '0995_01': '0995',
 '0997_01': '0997',
 '0998_01': '0998',
 '1000_01': '1000',
 '1001_01': '1001',
 '1002_01': '1002',
 '1002_02': '1002',
 '1002_03': '1002',
 '1004_01': '1004',
 '1005_01': '1005',
 '1006_01': '1006',
 '1006_02': '1006',
 '1006_03': '1006',
 '1008_01': '1008',
 '1008_02': '1008',
 '1011_01': '1011',
 '1011_02': '1011',
 '1012_01': '1012',
 '1013_01': '1013',
 '1014_01': '1014',
 '1015_01': '1015',
 '1017_01': '1017',
 '1018_01': '1018',
 '1019_01': '1019',
 '1020_01': '1020',
 '1022_01': '1022',
 '1024_01': '1024',
 '1024_02': '1024',
 '1024_03': '1024',
 '1024_04': '1024',
 '1025_01': '1025',
 '1026_01': '1026',
 '1027_01': '1027',
 '1027_02': '1027',
 '1027_03': '1027',
 '1027_04': '1027',
 '1029_01': '1029',
 '1030_01': '1030',
 '1031_01': '1031',
 '1032_01': '1032',
 '1033_01': '1033',
 '1034_01': '1034',
 '1035_01': '1035',
 '1036_01': '1036',
 '1038_01': '1038',
 '1040_01': '1040',
 '1041_01': '1041',
 '1043_01': '1043',
 '1045_01': '1045',
 '1045_02': '1045',
 '1046_01': '1046',
 '1047_01': '1047',
 '1048_01': '1048',
 '1049_01': '1049',
 '1049_02': '1049',
 '1051_01': '1051',
 '1052_01': '1052',
 '1053_01': '1053',
 '1054_01': '1054',
 '1056_01': '1056',
 '1056_02': '1056',
 '1057_01': '1057',
 '1058_01': '1058',
 '1060_01': '1060',
 '1062_01': '1062',
 '1063_01': '1063',

In [16]:
data['PGroup'] = data['PassengerId'].map(dic_id)

In [24]:
data['HomePlanet'] = data['HomePlanet'].fillna(data.groupby('PGroup')['HomePlanet'].transform(pd.Series.mode))

In [25]:
data[data['HomePlanet'].isnull()]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Total_cost,PGroup
59,0064_02,NaN,True,E/3/S,TRAPPIST-1e,33.0,False,0.0,0.0,NaN,0.0,0.0,Colatz Keen,True,0.0,0064
113,0119_01,NaN,False,A/0/P,TRAPPIST-1e,39.0,False,0.0,2344.0,0.0,65.0,6898.0,Batan Coning,False,9307.0,0119
186,0210_01,NaN,True,D/6/P,55 Cancri e,24.0,False,0.0,0.0,NaN,0.0,0.0,Arraid Inicont,True,0.0,0210
225,0242_01,NaN,False,F/46/S,TRAPPIST-1e,18.0,False,313.0,1.0,691.0,283.0,0.0,Almone Sté,False,1288.0,0242
234,0251_01,NaN,True,C/11/S,55 Cancri e,54.0,False,0.0,0.0,0.0,0.0,0.0,Diphah Amsive,True,0.0,0251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8515,9084_01,NaN,False,E/582/P,TRAPPIST-1e,25.0,False,1258.0,0.0,22.0,19.0,0.0,Jurs Mone,False,1299.0,9084
8613,9194_01,NaN,False,E/603/S,55 Cancri e,53.0,False,0.0,4017.0,0.0,13.0,3147.0,NaN,False,7177.0,9194
8666,9248_01,NaN,False,F/1792/S,55 Cancri e,38.0,NaN,28.0,1208.0,973.0,207.0,0.0,Gian Perle,True,2416.0,9248
8674,9257_01,NaN,False,F/1892/P,TRAPPIST-1e,13.0,False,39.0,0.0,1085.0,24.0,0.0,Ties Apple,False,1148.0,9257
8684,9274_01,NaN,True,G/1508/P,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Chelsa Bullisey,True,0.0,9274

In [26]:
data.loc[58:60]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Total_cost,PGroup
58,0064_01,Mars,True,F/14/S,TRAPPIST-1e,15.0,False,0.0,0.0,0.0,0.0,0.0,NaN,True,0.0,0064
59,0064_02,NaN,True,E/3/S,TRAPPIST-1e,33.0,False,0.0,0.0,NaN,0.0,0.0,Colatz Keen,True,0.0,0064
60,0066_01,Earth,False,G/6/P,TRAPPIST-1e,62.0,False,1.0,153.0,197.0,0.0,460.0,Diandy Pecketton,False,811.0,0066

In [19]:
data.groupby(['PGroup','HomePlanet'])['Transported'].sum()

PGroup  HomePlanet
0001    Europa        0
0002    Earth         1
0003    Europa        0
0004    Earth         1
0005    Earth         1
                     ..
9275    Europa        2
9276    Europa        0
9278    Earth         0
9279    Earth         1
9280    Europa        1
Name: Transported, Length: 6107, dtype: int64

In [ ]:
data_cabin_pre = data['Cabin'].str.split('/', expand=True)

In [ ]:
data_cabin_pre[2].value_counts()

In [ ]:
data['Cabin_A'] = data_cabin = data['Cabin'].str.split('/', expand=True)[0]

In [ ]:
data['Cabin_B'] = data_cabin = data['Cabin'].str.split('/', expand=True)[2]

In [ ]:
data[data['Cabin'].isnull()]

In [ ]:
data

In [ ]:
data_cabin = data.groupby('Cabin_A')['Transported'].sum()

In [ ]:
data_cabin_B = data.groupby('Cabin_B')['Transported'].sum()

In [ ]:
data_cabin_B

In [ ]:
data_cabin_all = data['Cabin_A'].value_counts().sort_index()

In [ ]:
data_cabin_true = pd.DataFrame(data_cabin)

In [ ]:
data_cabin_total = pd.DataFrame(data_cabin_all)

In [ ]:
data_cabin_true.columns

In [ ]:
data_cabin_true['Total'] = data_cabin_total['Cabin_A']

In [ ]:
data_cabin_true['Ratio'] = data_cabin_true['Transported'] / data_cabin_true['Total']

In [ ]:
data_cabin_true

In [ ]:
data['TotalCost'] = data['RoomService'] + data['FoodCourt'] + data['ShoppingMall'] + data['Spa'] + data['VRDeck']

In [ ]:
data['TotalCost'].isnull().sum()

In [ ]:
data['TotalCost'].describe()

In [ ]:
data[data['TotalCost'] == 0].count()

In [ ]:
def CostGrade(c) :describe if c >

In [ ]:
data

# 수업

# 결측치 제거

PassengerId       0
HomePlanet      201 - 1. PassengerId 앞 4자리가 같으면 같을 것. 2. Name 의 lastName 이 같으면 같을 것. 3. 그래도 안채워지면, Destination에 따른 최빈값을 채우자
CryoSleep       217 - 1. 
Cabin           199 - 
Destination     182 - 
Age             179 - 
VIP             203 - F/T 최빈값(False)으로 채워~
RoomService     181 - TotalCost
FoodCourt       183 - TotalCost
ShoppingMall    208 - TotalCost
Spa             183 - TotalCost
VRDeck          188 - TotalCost
Name            200 - 안중요 날려
Transported       0

## HomePlanet

In [33]:
df = data.copy()
df['GroupId'] = df['PassengerId'].str[:4]

home_group = df.groupby(['GroupId', 'HomePlanet']).size().reset_index()

mapping = {}
for key, value in zip(home_group['GroupId'], home_group['HomePlanet']):
    mapping[key] = value

In [47]:
home_group

     GroupId HomePlanet  0
0       0001     Europa  1
1       0002      Earth  1
2       0003     Europa  2
3       0004      Earth  1
4       0005      Earth  1
...      ...        ... ..
6102    9275     Europa  3
6103    9276     Europa  1
6104    9278      Earth  1
6105    9279      Earth  1
6106    9280     Europa  2

[6107 rows x 3 columns]

In [34]:
mapping

{'0001': 'Europa',
 '0002': 'Earth',
 '0003': 'Europa',
 '0004': 'Earth',
 '0005': 'Earth',
 '0006': 'Earth',
 '0007': 'Earth',
 '0008': 'Europa',
 '0009': 'Mars',
 '0010': 'Earth',
 '0011': 'Earth',
 '0012': 'Earth',
 '0014': 'Mars',
 '0015': 'Earth',
 '0016': 'Mars',
 '0017': 'Earth',
 '0020': 'Earth',
 '0022': 'Mars',
 '0024': 'Europa',
 '0025': 'Earth',
 '0026': 'Europa',
 '0028': 'Mars',
 '0030': 'Earth',
 '0031': 'Mars',
 '0034': 'Europa',
 '0035': 'Mars',
 '0036': 'Earth',
 '0038': 'Earth',
 '0039': 'Earth',
 '0041': 'Earth',
 '0043': 'Europa',
 '0044': 'Earth',
 '0045': 'Mars',
 '0050': 'Earth',
 '0051': 'Earth',
 '0052': 'Earth',
 '0053': 'Earth',
 '0056': 'Europa',
 '0058': 'Earth',
 '0061': 'Earth',
 '0062': 'Earth',
 '0064': 'Mars',
 '0066': 'Earth',
 '0067': 'Earth',
 '0068': 'Mars',
 '0069': 'Earth',
 '0070': 'Earth',
 '0071': 'Earth',
 '0072': 'Earth',
 '0073': 'Mars',
 '0074': 'Europa',
 '0076': 'Mars',
 '0077': 'Mars',
 '0078': 'Europa',
 '0081': 'Earth',
 '0082': 'Mars',
 '0084': 'Earth',
 '0085': 'Europa',
 '0086': 'Earth',
 '0088': 'Mars',
 '0090': 'Earth',
 '0091': 'Earth',
 '0092': 'Earth',
 '0097': 'Europa',
 '0098': 'Earth',
 '0099': 'Earth',
 '0101': 'Mars',
 '0102': 'Earth',
 '0103': 'Earth',
 '0105': 'Earth',
 '0107': 'Mars',
 '0108': 'Earth',
 '0110': 'Europa',
 '0111': 'Europa',
 '0112': 'Europa',
 '0113': 'Earth',
 '0114': 'Earth',
 '0115': 'Mars',
 '0116': 'Europa',
 '0119': 'Europa',
 '0120': 'Mars',
 '0122': 'Earth',
 '0123': 'Earth',
 '0126': 'Mars',
 '0127': 'Mars',
 '0128': 'Mars',
 '0129': 'Earth',
 '0133': 'Mars',
 '0134': 'Earth',
 '0136': 'Earth',
 '0138': 'Earth',
 '0139': 'Europa',
 '0140': 'Earth',
 '0141': 'Mars',
 '0144': 'Earth',
 '0146': 'Earth',
 '0147': 'Earth',
 '0148': 'Mars',
 '0149': 'Earth',
 '0151': 'Earth',
 '0152': 'Earth',
 '0160': 'Earth',
 '0163': 'Europa',
 '0164': 'Earth',
 '0165': 'Mars',
 '0167': 'Mars',
 '0169': 'Earth',
 '0170': 'Earth',
 '0171': 'Earth',
 '0172': 'Earth',
 '0173': 'Earth',
 '0174': 'Earth',
 '0177': 'Europa',
 '0178': 'Mars',
 '0179': 'Earth',
 '0181': 'Earth',
 '0182': 'Europa',
 '0183': 'Earth',
 '0186': 'Earth',
 '0188': 'Earth',
 '0189': 'Earth',
 '0190': 'Earth',
 '0192': 'Earth',
 '0193': 'Mars',
 '0195': 'Mars',
 '0196': 'Mars',
 '0197': 'Europa',
 '0198': 'Earth',
 '0199': 'Earth',
 '0200': 'Earth',
 '0201': 'Europa',
 '0202': 'Europa',
 '0203': 'Europa',
 '0205': 'Earth',
 '0206': 'Europa',
 '0207': 'Earth',
 '0211': 'Mars',
 '0212': 'Earth',
 '0213': 'Earth',
 '0216': 'Earth',
 '0217': 'Earth',
 '0219': 'Earth',
 '0220': 'Earth',
 '0221': 'Mars',
 '0222': 'Mars',
 '0223': 'Earth',
 '0224': 'Mars',
 '0225': 'Earth',
 '0229': 'Earth',
 '0231': 'Mars',
 '0232': 'Earth',
 '0233': 'Mars',
 '0234': 'Earth',
 '0237': 'Europa',
 '0239': 'Mars',
 '0240': 'Mars',
 '0241': 'Europa',
 '0243': 'Earth',
 '0244': 'Mars',
 '0245': 'Europa',
 '0246': 'Mars',
 '0248': 'Europa',
 '0250': 'Earth',
 '0252': 'Earth',
 '0253': 'Earth',
 '0254': 'Earth',
 '0255': 'Europa',
 '0257': 'Mars',
 '0258': 'Earth',
 '0260': 'Europa',
 '0261': 'Earth',
 '0263': 'Earth',
 '0265': 'Europa',
 '0267': 'Earth',
 '0269': 'Earth',
 '0270': 'Earth',
 '0275': 'Europa',
 '0277': 'Earth',
 '0278': 'Earth',
 '0281': 'Earth',
 '0282': 'Earth',
 '0283': 'Earth',
 '0285': 'Europa',
 '0286': 'Earth',
 '0287': 'Europa',
 '0288': 'Earth',
 '0289': 'Europa',
 '0290': 'Europa',
 '0291': 'Europa',
 '0294': 'Europa',
 '0297': 'Earth',
 '0298': 'Europa',
 '0301': 'Earth',
 '0302': 'Earth',
 '0304': 'Europa',
 '0305': 'Europa',
 '0306': 'Earth',
 '0307': 'Earth',
 '0309': 'Earth',
 '0310': 'Europa',
 '0313': 'Earth',
 '0314': 'Earth',
 '0316': 'Europa',
 '0320': 'Earth',
 '0322': 'Earth',
 '0324': 'Earth',
 '0326': 'Earth',
 '0327': 'Earth',
 '0330': 'Europa',
 '0331': 'Earth',
 '0333': 'Mars',
 '0334': 'Mars',
 '0336': 'Earth',
 '0337': 'Mars',
 '0338': 'Earth',
 '0340': 'Europa',
 '0341': 'Earth',
 '0343': 'Earth',
 '0345': 'Mars',
 '0346': 'Earth',
 '0347': 'Mars',
 '0348': 'Mars',
 '0350': 'Earth',
 '0352': 'Mars',
 '0355': 'Earth',
 '0356': 'Europa',
 '0357': 'Earth',
 '0358': 'Earth',
 '0359': 'Earth',
 '0360': 'Earth',
 '0361': 'Earth',
 '0365': 'Earth',
 '0368': 'Mars',
 '0369': 'Earth',
 '0370': 'Earth',
 '0371': 'Mars',
 '0372': 'Earth',
 '0373': 'Earth',
 '0375': 'Earth',
 '0376': 'Earth',
 '0377': 'Europa',
 '0378': 'Europa',
 '0379': 'Earth',
 '0380': 'Europa',
 '0381': 'Europa',
 '0383': 'Earth',
 '0384': 'Earth',
 '0385': 'Earth',
 '0387': 'Earth',
 '0388': 'Earth',
 '0389': 'Earth',
 '0391': 'Europa',
 '0392': 'Earth',
 '0395': 'Europa',
 '0396': 'Earth',
 '0397': 'Mars',
 '0398': 'Mars',
 '0401': 'Mars',
 '0403': 'Mars',
 '0405': 'Earth',
 '0407': 'Earth',
 '0408': 'Mars',
 '0409': 'Mars',
 '0410': 'Earth',
 '0411': 'Earth',
 '0412': 'Europa',
 '0413': 'Earth',
 '0415': 'Earth',
 '0417': 'Europa',
 '0423': 'Europa',
 '0425': 'Mars',
 '0427': 'Europa',
 '0428': 'Europa',
 '0429': 'Europa',
 '0430': 'Earth',
 '0431': 'Mars',
 '0432': 'Mars',
 '0433': 'Europa',
 '0434': 'Mars',
 '0435': 'Earth',
 '0436': 'Earth',
 '0437': 'Earth',
 '0438': 'Europa',
 '0439': 'Europa',
 '0441': 'Earth',
 '0442': 'Earth',
 '0444': 'Mars',
 '0445': 'Earth',
 '0446': 'Europa',
 '0447': 'Earth',
 '0448': 'Earth',
 '0449': 'Earth',
 '0452': 'Mars',
 '0453': 'Europa',
 '0454': 'Europa',
 '0456': 'Earth',
 '0457': 'Earth',
 '0458': 'Europa',
 '0459': 'Earth',
 '0460': 'Earth',
 '0461': 'Earth',
 '0462': 'Earth',
 '0463': 'Mars',
 '0465': 'Earth',
 '0466': 'Earth',
 '0468': 'Earth',
 '0470': 'Mars',
 '0471': 'Europa',
 '0472': 'Earth',
 '0474': 'Earth',
 '0475': 'Earth',
 '0476': 'Mars',
 '0477': 'Earth',
 '0480': 'Earth',
 '0481': 'Earth',
 '0482': 'Earth',
 '0485': 'Europa',
 '0487': 'Europa',
 '0488': 'Earth',
 '0490': 'Earth',
 '0498': 'Europa',
 '0499': 'Mars',
 '0500': 'Mars',
 '0501': 'Europa',
 '0502': 'Mars',
 '0503': 'Mars',
 '0504': 'Europa',
 '0506': 'Mars',
 '0507': 'Earth',
 '0510': 'Europa',
 '0512': 'Europa',
 '0513': 'Earth',
 '0515': 'Europa',
 '0516': 'Europa',
 '0517': 'Earth',
 '0519': 'Earth',
 '0520': 'Earth',
 '0521': 'Earth',
 '0522': 'Earth',
 '0523': 'Earth',
 '0525': 'Earth',
 '0527': 'Mars',
 '0528': 'Europa',
 '0529': 'Earth',
 '0531': 'Earth',
 '0533': 'Mars',
 '0534': 'Europa',
 '0537': 'Earth',
 '0538': 'Earth',
 '0539': 'Europa',
 '0540': 'Mars',
 '0542': 'Earth',
 '0545': 'Earth',
 '0546': 'Earth',
 '0547': 'Earth',
 '0548': 'Earth',
 '0549': 'Mars',
 '0550': 'Earth',
 '0551': 'Earth',
 '0552': 'Europa',
 '0553': 'Europa',
 '0555': 'Europa',
 '0556': 'Earth',
 '0559': 'Earth',
 '0560': 'Earth',
 '0561': 'Earth',
 '0563': 'Mars',
 '0564': 'Europa',
 '0565': 'Mars',
 '0566': 'Mars',
 '0567': 'Earth',
 '0568': 'Europa',
 '0569': 'Earth',
 '0570': 'Europa',
 '0571': 'Europa',
 '0572': 'Earth',
 '0573': 'Earth',
 '0575': 'Europa',
 '0576': 'Earth',
 '0577': 'Earth',
 '0579': 'Earth',
 '0580': 'Earth',
 '0581': 'Earth',
 '0582': 'Mars',
 '0583': 'Mars',
 '0585': 'Mars',
 '0586': 'Europa',
 '0587': 'Mars',
 '0588': 'Earth',
 '0589': 'Earth',
 '0590': 'Earth',
 '0591': 'Earth',
 '0593': 'Mars',
 '0594': 'Earth',
 '0596': 'Mars',
 '0597': 'Earth',
 '0598': 'Earth',
 '0599': 'Mars',
 '0600': 'Europa',
 '0602': 'Mars',
 '0603': 'Earth',
 '0607': 'Europa',
 '0608': 'Earth',
 '0609': 'Mars',
 '0610': 'Earth',
 '0611': 'Earth',
 '0612': 'Europa',
 '0614': 'Earth',
 '0615': 'Earth',
 '0618': 'Earth',
 '0619': 'Europa',
 '0623': 'Earth',
 '0628': 'Earth',
 '0629': 'Earth',
 '0630': 'Mars',
 '0631': 'Mars',
 '0633': 'Mars',
 '0634': 'Earth',
 '0635': 'Earth',
 '0636': 'Earth',
 '0637': 'Mars',
 '0638': 'Europa',
 '0639': 'Earth',
 '0641': 'Earth',
 '0642': 'Europa',
 '0643': 'Mars',
 '0644': 'Europa',
 '0645': 'Earth',
 '0646': 'Europa',
 '0647': 'Mars',
 '0650': 'Earth',
 '0653': 'Mars',
 '0655': 'Mars',
 '0656': 'Earth',
 '0657': 'Earth',
 '0658': 'Earth',
 '0659': 'Earth',
 '0660': 'Earth',
 '0661': 'Europa',
 '0663': 'Earth',
 '0664': 'Europa',
 '0665': 'Mars',
 '0668': 'Earth',
 '0669': 'Earth',
 '0671': 'Earth',
 '0672': 'Earth',
 '0674': 'Earth',
 '0677': 'Earth',
 '0678': 'Earth',
 '0679': 'Earth',
 '0680': 'Earth',
 '0682': 'Mars',
 '0683': 'Mars',
 '0684': 'Mars',
 '0685': 'Earth',
 '0686': 'Mars',
 '0687': 'Mars',
 '0688': 'Mars',
 '0689': 'Europa',
 '0690': 'Mars',
 '0691': 'Mars',
 '0693': 'Europa',
 '0696': 'Earth',
 '0697': 'Earth',
 '0699': 'Mars',
 '0701': 'Europa',
 '0702': 'Earth',
 '0703': 'Earth',
 '0704': 'Earth',
 '0705': 'Earth',
 '0707': 'Earth',
 '0709': 'Europa',
 '0710': 'Mars',
 '0712': 'Mars',
 '0713': 'Earth',
 '0714': 'Earth',
 '0715': 'Europa',
 '0718': 'Earth',
 '0719': 'Mars',
 '0724': 'Earth',
 '0726': 'Earth',
 '0727': 'Earth',
 '0728': 'Earth',
 '0729': 'Earth',
 '0732': 'Earth',
 '0733': 'Earth',
 '0734': 'Earth',
 '0736': 'Earth',
 '0737': 'Europa',
 '0738': 'Mars',
 '0740': 'Europa',
 '0743': 'Earth',
 '0746': 'Earth',
 '0750': 'Earth',
 '0753': 'Europa',
 '0754': 'Europa',
 '0756': 'Europa',
 '0757': 'Mars',
 '0761': 'Europa',
 '0762': 'Earth',
 '0764': 'Earth',
 '0765': 'Mars',
 '0767': 'Earth',
 '0768': 'Europa',
 '0769': 'Europa',
 '0770': 'Earth',
 '0771': 'Earth',
 '0772': 'Europa',
 '0773': 'Earth',
 '0776': 'Earth',
 '0777': 'Europa',
 '0779': 'Earth',
 '0781': 'Earth',
 '0782': 'Mars',
 '0784': 'Europa',
 '0785': 'Earth',
 '0786': 'Earth',
 '0787': 'Earth',
 '0788': 'Earth',
 '0789': 'Europa',
 '0790': 'Earth',
 '0791': 'Earth',
 '0793': 'Earth',
 '0794': 'Mars',
 '0795': 'Earth',
 '0796': 'Europa',
 '0797': 'Earth',
 '0798': 'Mars',
 '0799': 'Europa',
 '0802': 'Mars',
 '0805': 'Europa',
 '0806': 'Earth',
 '0808': 'Earth',
 '0809': 'Mars',
 '0811': 'Mars',
 '0813': 'Mars',
 '0815': 'Earth',
 '0816': 'Europa',
 '0817': 'Earth',
 '0818': 'Europa',
 '0819': 'Earth',
 '0820': 'Earth',
 '0822': 'Earth',
 '0823': 'Earth',
 '0824': 'Mars',
 '0825': 'Earth',
 '0826': 'Earth',
 '0828': 'Earth',
 '0829': 'Earth',
 '0830': 'Earth',
 '0833': 'Europa',
 '0834': 'Earth',
 '0835': 'Earth',
 '0836': 'Mars',
 '0839': 'Europa',
 '0840': 'Earth',
 '0845': 'Europa',
 '0846': 'Earth',
 '0848': 'Mars',
 '0849': 'Europa',
 '0850': 'Mars',
 '0851': 'Earth',
 '0859': 'Earth',
 '0860': 'Earth',
 '0863': 'Earth',
 '0865': 'Europa',
 '0867': 'Earth',
 '0868': 'Earth',
 '0869': 'Earth',
 '0870': 'Earth',
 '0871': 'Europa',
 '0873': 'Earth',
 '0874': 'Earth',
 '0875': 'Earth',
 '0876': 'Earth',
 '0877': 'Europa',
 '0878': 'Mars',
 '0879': 'Earth',
 '0881': 'Europa',
 '0883': 'Earth',
 '0885': 'Earth',
 '0889': 'Europa',
 '0890': 'Mars',
 '0893': 'Earth',
 '0898': 'Earth',
 '0899': 'Earth',
 '0901': 'Mars',
 '0902': 'Earth',
 '0903': 'Earth',
 '0904': 'Europa',
 '0905': 'Mars',
 '0906': 'Earth',
 '0907': 'Europa',
 '0910': 'Earth',
 '0911': 'Mars',
 '0912': 'Europa',
 '0913': 'Europa',
 '0915': 'Earth',
 '0918': 'Earth',
 '0919': 'Earth',
 '0921': 'Earth',
 '0922': 'Europa',
 '0923': 'Europa',
 '0924': 'Earth',
 '0925': 'Mars',
 '0926': 'Europa',
 '0927': 'Earth',
 '0928': 'Earth',
 '0930': 'Earth',
 '0931': 'Earth',
 '0932': 'Mars',
 '0933': 'Europa',
 '0935': 'Earth',
 '0938': 'Earth',
 '0939': 'Earth',
 '0940': 'Earth',
 '0941': 'Earth',
 '0942': 'Mars',
 '0944': 'Earth',
 '0946': 'Earth',
 '0947': 'Earth',
 '0949': 'Earth',
 '0951': 'Earth',
 '0952': 'Mars',
 '0953': 'Earth',
 '0955': 'Earth',
 '0956': 'Earth',
 '0957': 'Mars',
 '0960': 'Earth',
 '0961': 'Earth',
 '0964': 'Europa',
 '0965': 'Mars',
 '0966': 'Earth',
 '0968': 'Earth',
 '0969': 'Mars',
 '0970': 'Earth',
 '0971': 'Earth',
 '0972': 'Earth',
 '0975': 'Earth',
 '0976': 'Earth',
 '0978': 'Earth',
 '0979': 'Europa',
 '0982': 'Earth',
 '0983': 'Earth',
 '0984': 'Earth',
 '0985': 'Earth',
 '0987': 'Earth',
 '0988': 'Earth',
 '0989': 'Earth',
 '0990': 'Earth',
 '0991': 'Earth',
 '0992': 'Europa',
 '0993': 'Earth',
 '0994': 'Earth',
 '0995': 'Europa',
 '0997': 'Mars',
 '0998': 'Europa',
 '1000': 'Mars',
 '1001': 'Earth',
 '1002': 'Mars',
 '1004': 'Europa',
 '1005': 'Earth',
 '1006': 'Earth',
 '1008': 'Europa',
 '1011': 'Earth',
 '1012': 'Earth',
 '1013': 'Earth',
 '1014': 'Mars',
 '1015': 'Earth',
 '1017': 'Earth',
 '1018': 'Earth',
 '1019': 'Earth',
 '1020': 'Mars',
 '1022': 'Earth',
 '1024': 'Earth',
 '1025': 'Earth',
 '1026': 'Earth',
 '1027': 'Mars',
 '1029': 'Mars',
 '1030': 'Earth',
 '1031': 'Earth',
 '1032': 'Earth',
 '1033': 'Earth',
 '1034': 'Earth',
 '1035': 'Mars',
 '1036': 'Earth',
 '1038': 'Earth',
 '1040': 'Earth',
 '1041': 'Europa',
 '1043': 'Earth',
 '1045': 'Europa',
 '1046': 'Earth',
 '1047': 'Earth',
 '1048': 'Earth',
 '1049': 'Mars',
 '1051': 'Earth',
 '1052': 'Earth',
 '1053': 'Earth',
 '1054': 'Earth',
 '1056': 'Mars',
 '1057': 'Europa',
 '1058': 'Earth',
 '1060': 'Earth',
 '1062': 'Earth',
 '1063': 'Europa',
 '1065': 'Mars',
 '1066': 'Mars',
 '1068': 'Earth',
 '1075': 'Europa',
 '1076': 'Earth',
 '1077': 'Earth',
 '1078': 'Earth',
 '1079': 'Earth',
 '1080': 'Mars',
 '1082': 'Mars',
 '1083': 'Mars',
 '1084': 'Earth',
 '1085': 'Earth',
 '1086': 'Earth',
 '1088': 'Earth',
 '1089': 'Europa',
 '1091': 'Mars',
 '1093': 'Mars',
 '1094': 'Earth',
 '1095': 'Europa',
 '1096': 'Earth',
 '1097': 'Mars',
 '1099': 'Earth',
 '1100': 'Mars',
 '1102': 'Mars',
 '1105': 'Earth',
 '1108': 'Mars',
 '1110': 'Europa',
 '1112': 'Europa',
 '1113': 'Earth',
 '1114': 'Mars',
 '1115': 'Earth',
 '1116': 'Earth',
 '1117': 'Earth',
 '1121': 'Earth',
 '1123': 'Europa',
 '1127': 'Europa',
 '1129': 'Earth',
 '1130': 'Mars',
 '1132': 'Earth',
 '1133': 'Mars',
 '1134': 'Europa',
 '1136': 'Earth',
 '1140': 'Europa',
 '1141': 'Earth',
 '1142': 'Earth',
 '1144': 'Earth',
 '1146': 'Earth',
 '1147': 'Europa',
 '1148': 'Europa',
 '1149': 'Earth',
 '1150': 'Earth',
 '1152': 'Mars',
 '1153': 'Earth',
 '1154': 'Europa',
 '1155': 'Earth',
 '1156': 'Europa',
 '1161': 'Europa',
 '1162': 'Europa',
 '1163': 'Earth',
 '1165': 'Europa',
 '1166': 'Europa',
 '1167': 'Mars',
 '1168': 'Earth',
 '1169': 'Mars',
 '1170': 'Earth',
 '1173': 'Earth',
 '1174': 'Earth',
 '1175': 'Mars',
 '1177': 'Europa',
 '1178': 'Earth',
 '1179': 'Europa',
 '1180': 'Earth',
 '1182': 'Mars',
 '1185': 'Mars',
 '1186': 'Earth',
 '1187': 'Earth',
 '1188': 'Europa',
 '1190': 'Earth',
 '1191': 'Earth',
 '1192': 'Earth',
 '1193': 'Europa',
 '1195': 'Earth',
 '1197': 'Europa',
 '1198': 'Mars',
 '1199': 'Earth',
 '1203': 'Europa',
 '1206': 'Earth',
 '1208': 'Earth',
 '1210': 'Earth',
 '1211': 'Earth',
 '1212': 'Earth',
 '1213': 'Earth',
 '1214': 'Earth',
 '1215': 'Earth',
 '1216': 'Earth',
 '1218': 'Earth',
 '1220': 'Europa',
 '1221': 'Earth',
 '1222': 'Earth',
 '1223': 'Europa',
 '1225': 'Earth',
 '1228': 'Mars',
 '1229': 'Earth',
 '1230': 'Earth',
 '1231': 'Mars',
 '1232': 'Europa',
 '1233': 'Earth',
 '1234': 'Earth',
 '1235': 'Earth',
 '1236': 'Earth',
 '1238': 'Europa',
 '1239': 'Earth',
 '1240': 'Earth',
 '1242': 'Europa',
 '1243': 'Europa',
 '1246': 'Earth',
 '1248': 'Earth',
 '1250': 'Earth',
 '1254': 'Mars',
 '1255': 'Mars',
 '1256': 'Mars',
 '1258': 'Europa',
 '1259': 'Earth',
 '1260': 'Earth',
 '1261': 'Europa',
 '1263': 'Mars',
 '1264': 'Earth',
 '1267': 'Earth',
 '1269': 'Mars',
 '1271': 'Earth',
 '1273': 'Earth',
 '1274': 'Earth',
 '1278': 'Earth',
 '1279': 'Europa',
 '1280': 'Earth',
 '1281': 'Earth',
 '1282': 'Earth',
 '1283': 'Earth',
 '1284': 'Mars',
 '1285': 'Earth',
 '1286': 'Mars',
 '1287': 'Mars',
 '1288': 'Earth',
 '1289': 'Earth',
 '1291': 'Mars',
 '1292': 'Europa',
 '1293': 'Earth',
 '1294': 'Europa',
 '1295': 'Earth',
 '1299': 'Earth',
 '1300': 'Earth',
 '1302': 'Mars',
 '1304': 'Earth',
 '1306': 'Europa',
 '1307': 'Earth',
 '1308': 'Europa',
 '1309': 'Earth',
 '1310': 'Europa',
 '1311': 'Mars',
 '1312': 'Earth',
 '1316': 'Europa',
 '1317': 'Mars',
 '1322': 'Earth',
 '1323': 'Earth',
 '1324': 'Earth',
 '1325': 'Earth',
 '1326': 'Mars',
 '1328': 'Earth',
 '1330': 'Mars',
 '1331': 'Earth',
 '1332': 'Earth',
 '1333': 'Earth',
 '1335': 'Earth',
 '1336': 'Earth',
 '1337': 'Earth',
 '1340': 'Earth',
 '1342': 'Earth',
 '1345': 'Earth',
 '1348': 'Europa',
 '1350': 'Earth',
 '1351': 'Earth',
 '1352': 'Mars',
 '1353': 'Mars',
 '1355': 'Earth',
 '1356': 'Earth',
 '1357': 'Mars',
 '1360': 'Earth',
 '1362': 'Earth',
 '1365': 'Europa',
 '1366': 'Earth',
 '1368': 'Earth',
 '1370': 'Earth',
 '1371': 'Mars',
 '1375': 'Earth',
 '1376': 'Earth',
 '1377': 'Europa',
 '1378': 'Earth',
 '1379': 'Earth',
 '1380': 'Europa',
 '1381': 'Earth',
 '1382': 'Earth',
 '1383': 'Europa',
 '1384': 'Earth',
 '1386': 'Earth',
 '1387': 'Mars',
 '1389': 'Earth',
 '1390': 'Earth',
 '1391': 'Mars',
 '1393': 'Mars',
 '1395': 'Earth',
 '1397': 'Earth',
 '1398': 'Earth',
 '1399': 'Earth',
 '1400': 'Earth',
 '1401': 'Earth',
 '1402': 'Earth',
 '1403': 'Earth',
 '1404': 'Europa',
 '1406': 'Mars',
 '1407': 'Earth',
 '1408': 'Earth',
 '1410': 'Earth',
 '1412': 'Earth',
 '1413': 'Earth',
 '1414': 'Earth',
 '1415': 'Europa',
 '1416': 'Earth',
 '1417': 'Europa',
 '1419': 'Mars',
 '1420': 'Mars',
 '1421': 'Mars',
 '1423': 'Europa',
 '1424': 'Europa',
 '1425': 'Earth',
 '1426': 'Europa',
 '1427': 'Mars',
 '1428': 'Earth',
 '1430': 'Earth',
 '1431': 'Earth',
 '1433': 'Earth',
 '1434': 'Earth',
 '1435': 'Earth',
 '1438': 'Earth',
 '1439': 'Mars',
 '1440': 'Earth',
 '1442': 'Earth',
 '1443': 'Earth',
 '1444': 'Europa',
 '1445': 'Earth',
 '1447': 'Earth',
 '1450': 'Europa',
 '1451': 'Europa',
 '1452': 'Europa',
 '1453': 'Earth',
 '1454': 'Europa',
 '1455': 'Europa',
 '1457': 'Earth',
 '1460': 'Earth',
 '1461': 'Earth',
 '1462': 'Earth',
 '1463': 'Earth',
 '1465': 'Earth',
 '1474': 'Mars',
 '1478': 'Earth',
 '1479': 'Mars',
 '1481': 'Mars',
 '1484': 'Earth',
 '1485': 'Mars',
 '1488': 'Mars',
 '1489': 'Earth',
 '1490': 'Europa',
 '1491': 'Earth',
 '1493': 'Earth',
 '1498': 'Earth',
 '1499': 'Earth',
 '1500': 'Earth',
 '1501': 'Earth',
 '1503': 'Mars',
 '1506': 'Earth',
 '1507': 'Earth',
 '1509': 'Mars',
 '1510': 'Mars',
 '1511': 'Europa',
 '1515': 'Earth',
 '1520': 'Earth',
 '1521': 'Mars',
 '1523': 'Europa',
 '1524': 'Earth',
 '1525': 'Mars',
 '1526': 'Earth',
 '1527': 'Europa',
 '1528': 'Mars',
 '1529': 'Europa',
 '1531': 'Earth',
 ...}

In [37]:
df['HomePlanet'].fillna(df['GroupId'].map(mapping), inplace = True)

In [39]:
df['HomePlanet'].isnull().sum()

111

In [41]:
df[df['HomePlanet'].isnull()]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId
186,0210_01,NaN,True,D/6/P,55 Cancri e,24.0,False,0.0,0.0,NaN,0.0,0.0,Arraid Inicont,True,0210
225,0242_01,NaN,False,F/46/S,TRAPPIST-1e,18.0,False,313.0,1.0,691.0,283.0,0.0,Almone Sté,False,0242
234,0251_01,NaN,True,C/11/S,55 Cancri e,54.0,False,0.0,0.0,0.0,0.0,0.0,Diphah Amsive,True,0251
274,0303_01,NaN,True,G/41/S,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Oraryn Kirklander,True,0303
286,0315_01,NaN,True,G/42/S,PSO J318.5-22,35.0,False,0.0,0.0,0.0,0.0,0.0,Adriet Valezaley,True,0315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8468,9043_01,NaN,True,F/1848/P,TRAPPIST-1e,25.0,False,0.0,0.0,0.0,0.0,0.0,Cobix Erle,True,9043
8515,9084_01,NaN,False,E/582/P,TRAPPIST-1e,25.0,False,1258.0,0.0,22.0,19.0,0.0,Jurs Mone,False,9084
8666,9248_01,NaN,False,F/1792/S,55 Cancri e,38.0,NaN,28.0,1208.0,973.0,207.0,0.0,Gian Perle,True,9248
8674,9257_01,NaN,False,F/1892/P,TRAPPIST-1e,13.0,False,39.0,0.0,1085.0,24.0,0.0,Ties Apple,False,9257
8684,9274_01,NaN,True,G/1508/P,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Chelsa Bullisey,True,9274

In [44]:
df['lastName'] = df['Name'].str.split(' ', expand = True)[1]

In [49]:
family_group = df.groupby(['lastName', 'HomePlanet']).size().reset_index()

family_map = {}
for key, value in zip(family_group['lastName'], family_group['HomePlanet']):
    family_map[key] = value
    
df['HomePlanet'].fillna(df['lastName'].map(family_map), inplace = True)

In [53]:
family_group[family_group['lastName'].duplicated()] # 중복값이 없으니깐 사용해도 된다!

Empty DataFrame
Columns: [lastName, HomePlanet, 0]
Index: []

In [50]:
df['HomePlanet'].isnull().sum()

12

In [51]:
df[df['HomePlanet'].isnull()]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId,lastName
225,0242_01,NaN,False,F/46/S,TRAPPIST-1e,18.0,False,313.0,1.0,691.0,283.0,0.0,Almone Sté,False,0242,Sté
234,0251_01,NaN,True,C/11/S,55 Cancri e,54.0,False,0.0,0.0,0.0,0.0,0.0,Diphah Amsive,True,0251,Amsive
807,0853_01,NaN,True,A/9/S,55 Cancri e,38.0,False,0.0,0.0,0.0,0.0,0.0,Hamelik Ageurante,True,0853,Ageurante
1855,1978_01,NaN,True,G/311/S,TRAPPIST-1e,19.0,False,0.0,0.0,0.0,0.0,0.0,NaN,True,1978,NaN
2274,2443_01,NaN,False,D/72/P,TRAPPIST-1e,31.0,False,1458.0,421.0,76.0,0.0,0.0,NaN,False,2443,NaN
2631,2817_01,NaN,False,F/584/P,TRAPPIST-1e,25.0,False,237.0,0.0,910.0,0.0,12.0,Sealfs Sutty,False,2817,Sutty
3091,3331_01,NaN,False,F/631/S,TRAPPIST-1e,40.0,False,666.0,4.0,83.0,0.0,50.0,NaN,True,3331,NaN
4548,4840_01,NaN,True,F/915/S,TRAPPIST-1e,36.0,False,0.0,0.0,NaN,0.0,0.0,NaN,True,4840,NaN
5252,5603_01,NaN,False,E/365/S,TRAPPIST-1e,34.0,False,170.0,1256.0,0.0,3926.0,7121.0,Kocha Cluitty,False,5603,Cluitty
5634,5989_01,NaN,False,F/1141/S,TRAPPIST-1e,20.0,False,0.0,0.0,NaN,703.0,0.0,Darrie Holcompton,False,5989,Holcompton
5762,6108_01,NaN,False,F/1166/S,TRAPPIST-1e,13.0,False,206.0,28.0,0.0,1.0,629.0,NaN,False,6108,NaN
6644,7006_01,NaN,True,G/1142/S,PSO J318.5-22,16.0,False,0.0,0.0,0.0,0.0,0.0,Tammyl Fuenton,True,7006,Fuenton

In [56]:
df[df['lastName']=='Amsive'] # 그룹도, 성도 한명씩 밖에 없네.. ㅠㅠ Destinatin

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId,lastName
234,0251_01,NaN,True,C/11/S,55 Cancri e,54.0,False,0.0,0.0,0.0,0.0,0.0,Diphah Amsive,True,0251,Amsive

In [58]:
df.groupby(['Destination','HomePlanet']).size()

Destination    HomePlanet
55 Cancri e    Earth          700
               Europa         902
               Mars           196
PSO J318.5-22  Earth          725
               Europa          19
               Mars            51
TRAPPIST-1e    Earth         3177
               Europa        1214
               Mars          1515
dtype: int64

In [59]:
desti_map = { '55 Cancri e' : 'Europa' , 'PSO J318.5-22' : 'Earth' , 'TRAPPIST-1e' : 'Earth' }

df['HomePlanet'].fillna(df['Destination'].map(desti_map), inplace = True)

In [61]:
df['HomePlanet'].isnull().sum()

0

## 먼저 VIP Null부터 처리

In [66]:
df['VIP'].value_counts() #최빈값으로 채우자

False    8494
True      199
Name: VIP, dtype: int64

In [67]:
df['VIP'].fillna(False, inplace=True)

In [68]:
df['VIP'].isnull().sum()

0

## 비용 5종 fee Null 처리

In [69]:
fee_list = ['RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']

In [70]:
for col in fee_list :
    df[col].fillna(df[col].median(), inplace=True)

In [71]:
df.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            200
Transported       0
GroupId           0
lastName        200
dtype: int64

In [91]:
df['fee'] = df['RoomService'] + df['FoodCourt'] + df['ShoppingMall'] + df['Spa'] + df['VRDeck']

## Cabin Null

In [73]:
df['deck'] = df['Cabin'].str.split('/').str[0]
df['side'] = df['Cabin'].str.split('/').str[-1]

In [74]:
df.groupby(['HomePlanet','deck']).size()

HomePlanet  deck
Earth       D          1
            E        404
            F       1652
            G       2559
Europa      A        256
            B        779
            C        747
            D        192
            E        133
            T          5
Mars        D        285
            E        339
            F       1142
dtype: int64

In [76]:
df['deck'].fillna(df['HomePlanet'].map({'Earth' : 'G', 'Europa' : 'B', 'Mars' : 'F'}), inplace = True)

In [77]:
df.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            200
Transported       0
GroupId           0
lastName        200
deck              0
side            199
dtype: int64

In [80]:
side_group = df.groupby(['GroupId','side']).size().reset_index()

In [86]:
side_group[side_group['GroupId'] == '0008']

  GroupId side  0
7    0008    P  3

In [82]:
side_group[side_group['GroupId'].duplicated()]

Empty DataFrame
Columns: [GroupId, side, 0]
Index: []

In [83]:
side_map = {}
for i,j in zip(side_group['GroupId'],side_group['side']) :
    side_map[i] = j

In [87]:
side_map

{'0001': 'P',
 '0002': 'S',
 '0003': 'S',
 '0004': 'S',
 '0005': 'P',
 '0006': 'S',
 '0007': 'S',
 '0008': 'P',
 '0009': 'P',
 '0010': 'S',
 '0011': 'P',
 '0014': 'P',
 '0015': 'P',
 '0016': 'P',
 '0017': 'P',
 '0020': 'S',
 '0022': 'P',
 '0024': 'S',
 '0025': 'S',
 '0026': 'P',
 '0028': 'P',
 '0030': 'S',
 '0031': 'P',
 '0034': 'S',
 '0035': 'P',
 '0036': 'S',
 '0038': 'S',
 '0039': 'P',
 '0041': 'P',
 '0043': 'P',
 '0044': 'P',
 '0045': 'P',
 '0050': 'S',
 '0051': 'S',
 '0052': 'S',
 '0053': 'S',
 '0056': 'S',
 '0058': 'S',
 '0061': 'S',
 '0062': 'S',
 '0064': 'S',
 '0066': 'P',
 '0067': 'S',
 '0068': 'S',
 '0069': 'S',
 '0070': 'P',
 '0071': 'P',
 '0072': 'S',
 '0073': 'P',
 '0074': 'S',
 '0076': 'S',
 '0077': 'P',
 '0078': 'S',
 '0081': 'S',
 '0082': 'P',
 '0084': 'S',
 '0085': 'S',
 '0086': 'P',
 '0088': 'S',
 '0090': 'S',
 '0091': 'S',
 '0092': 'P',
 '0097': 'S',
 '0098': 'P',
 '0099': 'P',
 '0102': 'S',
 '0103': 'S',
 '0105': 'P',
 '0107': 'S',
 '0108': 'S',
 '0110': 'P',
 '0111': 'S',
 '0112': 'S',
 '0113': 'P',
 '0114': 'S',
 '0115': 'P',
 '0116': 'P',
 '0119': 'P',
 '0120': 'P',
 '0122': 'S',
 '0123': 'P',
 '0126': 'S',
 '0127': 'S',
 '0128': 'S',
 '0129': 'S',
 '0133': 'S',
 '0134': 'P',
 '0136': 'S',
 '0138': 'P',
 '0139': 'S',
 '0140': 'P',
 '0141': 'P',
 '0144': 'S',
 '0146': 'S',
 '0147': 'S',
 '0148': 'P',
 '0149': 'S',
 '0151': 'P',
 '0152': 'P',
 '0160': 'P',
 '0163': 'P',
 '0164': 'S',
 '0165': 'P',
 '0167': 'S',
 '0169': 'P',
 '0170': 'S',
 '0171': 'S',
 '0172': 'P',
 '0173': 'S',
 '0174': 'P',
 '0177': 'S',
 '0178': 'S',
 '0179': 'P',
 '0181': 'P',
 '0182': 'P',
 '0183': 'S',
 '0186': 'P',
 '0188': 'S',
 '0189': 'P',
 '0190': 'S',
 '0192': 'P',
 '0193': 'P',
 '0195': 'P',
 '0196': 'P',
 '0197': 'P',
 '0198': 'P',
 '0199': 'S',
 '0200': 'P',
 '0201': 'S',
 '0202': 'P',
 '0203': 'S',
 '0205': 'S',
 '0206': 'S',
 '0207': 'P',
 '0210': 'P',
 '0211': 'P',
 '0212': 'P',
 '0213': 'P',
 '0216': 'S',
 '0217': 'P',
 '0219': 'P',
 '0220': 'P',
 '0221': 'S',
 '0222': 'S',
 '0223': 'S',
 '0224': 'S',
 '0225': 'P',
 '0229': 'S',
 '0231': 'S',
 '0232': 'S',
 '0233': 'S',
 '0234': 'P',
 '0237': 'P',
 '0240': 'P',
 '0241': 'P',
 '0242': 'S',
 '0243': 'S',
 '0244': 'S',
 '0245': 'P',
 '0246': 'P',
 '0248': 'S',
 '0250': 'S',
 '0251': 'S',
 '0252': 'P',
 '0253': 'P',
 '0254': 'P',
 '0255': 'S',
 '0257': 'S',
 '0258': 'S',
 '0260': 'S',
 '0261': 'P',
 '0263': 'P',
 '0265': 'S',
 '0267': 'S',
 '0269': 'S',
 '0270': 'P',
 '0275': 'S',
 '0277': 'P',
 '0278': 'P',
 '0281': 'P',
 '0282': 'S',
 '0283': 'P',
 '0285': 'P',
 '0286': 'P',
 '0287': 'P',
 '0288': 'S',
 '0289': 'S',
 '0290': 'S',
 '0291': 'S',
 '0294': 'S',
 '0297': 'P',
 '0298': 'P',
 '0302': 'P',
 '0303': 'S',
 '0304': 'S',
 '0305': 'P',
 '0306': 'S',
 '0307': 'S',
 '0309': 'S',
 '0313': 'P',
 '0314': 'P',
 '0315': 'S',
 '0316': 'S',
 '0320': 'S',
 '0321': 'S',
 '0322': 'S',
 '0324': 'P',
 '0326': 'S',
 '0330': 'S',
 '0331': 'P',
 '0333': 'P',
 '0334': 'S',
 '0336': 'P',
 '0337': 'S',
 '0338': 'S',
 '0340': 'S',
 '0341': 'P',
 '0343': 'P',
 '0345': 'S',
 '0346': 'P',
 '0347': 'S',
 '0348': 'P',
 '0350': 'P',
 '0352': 'P',
 '0356': 'P',
 '0357': 'S',
 '0358': 'S',
 '0359': 'S',
 '0360': 'S',
 '0361': 'S',
 '0365': 'S',
 '0368': 'P',
 '0369': 'S',
 '0370': 'P',
 '0371': 'P',
 '0372': 'P',
 '0373': 'P',
 '0375': 'P',
 '0376': 'S',
 '0377': 'S',
 '0378': 'S',
 '0379': 'P',
 '0381': 'P',
 '0382': 'P',
 '0383': 'S',
 '0384': 'S',
 '0385': 'P',
 '0387': 'P',
 '0388': 'S',
 '0389': 'P',
 '0391': 'P',
 '0392': 'P',
 '0395': 'P',
 '0396': 'S',
 '0397': 'S',
 '0398': 'S',
 '0401': 'S',
 '0402': 'S',
 '0403': 'P',
 '0405': 'P',
 '0407': 'P',
 '0408': 'P',
 '0409': 'S',
 '0410': 'S',
 '0411': 'P',
 '0412': 'P',
 '0413': 'P',
 '0415': 'S',
 '0417': 'P',
 '0423': 'P',
 '0425': 'P',
 '0427': 'P',
 '0428': 'S',
 '0429': 'S',
 '0430': 'S',
 '0431': 'P',
 '0432': 'S',
 '0433': 'P',
 '0434': 'S',
 '0435': 'S',
 '0436': 'S',
 '0437': 'S',
 '0438': 'S',
 '0439': 'P',
 '0441': 'S',
 '0442': 'P',
 '0444': 'P',
 '0445': 'S',
 '0446': 'P',
 '0447': 'S',
 '0448': 'P',
 '0449': 'S',
 '0452': 'S',
 '0453': 'S',
 '0454': 'S',
 '0456': 'S',
 '0457': 'P',
 '0458': 'S',
 '0459': 'S',
 '0460': 'S',
 '0461': 'S',
 '0462': 'S',
 '0463': 'P',
 '0465': 'P',
 '0466': 'P',
 '0470': 'S',
 '0471': 'P',
 '0472': 'S',
 '0474': 'S',
 '0475': 'P',
 '0476': 'P',
 '0477': 'P',
 '0480': 'P',
 '0481': 'S',
 '0482': 'S',
 '0485': 'S',
 '0487': 'S',
 '0488': 'P',
 '0490': 'S',
 '0498': 'S',
 '0499': 'S',
 '0500': 'P',
 '0501': 'P',
 '0503': 'S',
 '0504': 'S',
 '0506': 'S',
 '0507': 'S',
 '0510': 'P',
 '0512': 'S',
 '0513': 'P',
 '0515': 'S',
 '0516': 'S',
 '0517': 'P',
 '0518': 'S',
 '0519': 'S',
 '0520': 'S',
 '0521': 'S',
 '0522': 'P',
 '0523': 'S',
 '0527': 'S',
 '0528': 'P',
 '0529': 'P',
 '0531': 'P',
 '0533': 'P',
 '0534': 'P',
 '0537': 'P',
 '0538': 'P',
 '0539': 'P',
 '0540': 'S',
 '0542': 'P',
 '0545': 'P',
 '0546': 'S',
 '0547': 'S',
 '0548': 'S',
 '0549': 'S',
 '0550': 'S',
 '0551': 'S',
 '0552': 'S',
 '0553': 'P',
 '0555': 'P',
 '0556': 'S',
 '0559': 'S',
 '0560': 'S',
 '0561': 'S',
 '0563': 'P',
 '0564': 'P',
 '0565': 'P',
 '0566': 'S',
 '0567': 'S',
 '0568': 'S',
 '0569': 'P',
 '0570': 'S',
 '0571': 'P',
 '0572': 'S',
 '0573': 'P',
 '0575': 'P',
 '0576': 'S',
 '0577': 'P',
 '0579': 'S',
 '0580': 'P',
 '0581': 'S',
 '0582': 'P',
 '0583': 'S',
 '0585': 'P',
 '0586': 'P',
 '0587': 'P',
 '0588': 'P',
 '0589': 'P',
 '0590': 'P',
 '0591': 'S',
 '0593': 'P',
 '0594': 'S',
 '0596': 'P',
 '0597': 'P',
 '0598': 'S',
 '0599': 'P',
 '0600': 'S',
 '0602': 'P',
 '0603': 'P',
 '0607': 'P',
 '0608': 'P',
 '0609': 'P',
 '0610': 'P',
 '0611': 'S',
 '0612': 'P',
 '0614': 'S',
 '0615': 'S',
 '0618': 'P',
 '0619': 'S',
 '0623': 'S',
 '0628': 'P',
 '0629': 'P',
 '0630': 'S',
 '0631': 'S',
 '0633': 'P',
 '0634': 'P',
 '0635': 'S',
 '0636': 'P',
 '0637': 'S',
 '0638': 'P',
 '0639': 'P',
 '0641': 'S',
 '0642': 'S',
 '0643': 'P',
 '0644': 'P',
 '0645': 'P',
 '0646': 'S',
 '0647': 'S',
 '0650': 'S',
 '0653': 'S',
 '0655': 'P',
 '0656': 'P',
 '0657': 'S',
 '0658': 'S',
 '0659': 'S',
 '0660': 'S',
 '0661': 'P',
 '0663': 'P',
 '0664': 'S',
 '0665': 'P',
 '0668': 'P',
 '0669': 'P',
 '0671': 'P',
 '0672': 'P',
 '0674': 'S',
 '0677': 'S',
 '0678': 'S',
 '0679': 'S',
 '0680': 'P',
 '0682': 'S',
 '0683': 'P',
 '0684': 'P',
 '0685': 'P',
 '0686': 'P',
 '0687': 'S',
 '0688': 'S',
 '0689': 'S',
 '0690': 'S',
 '0691': 'S',
 '0693': 'S',
 '0696': 'S',
 '0697': 'P',
 '0699': 'S',
 '0701': 'S',
 '0702': 'S',
 '0703': 'S',
 '0704': 'P',
 '0705': 'P',
 '0707': 'S',
 '0709': 'S',
 '0710': 'P',
 '0712': 'P',
 '0713': 'S',
 '0714': 'P',
 '0718': 'P',
 '0719': 'P',
 '0724': 'S',
 '0726': 'P',
 '0727': 'S',
 '0728': 'S',
 '0729': 'S',
 '0733': 'P',
 '0734': 'P',
 '0736': 'P',
 '0737': 'S',
 '0738': 'P',
 '0740': 'P',
 '0743': 'S',
 '0746': 'S',
 '0750': 'S',
 '0753': 'P',
 '0754': 'P',
 '0756': 'S',
 '0757': 'P',
 '0761': 'P',
 '0762': 'S',
 '0764': 'S',
 '0765': 'S',
 '0767': 'S',
 '0768': 'P',
 '0769': 'S',
 '0770': 'S',
 '0771': 'P',
 '0772': 'S',
 '0773': 'S',
 '0776': 'P',
 '0777': 'P',
 '0779': 'P',
 '0781': 'S',
 '0782': 'P',
 '0784': 'S',
 '0785': 'P',
 '0786': 'P',
 '0787': 'P',
 '0788': 'P',
 '0789': 'S',
 '0790': 'S',
 '0791': 'P',
 '0793': 'P',
 '0794': 'S',
 '0795': 'S',
 '0796': 'S',
 '0797': 'S',
 '0798': 'S',
 '0799': 'P',
 '0802': 'S',
 '0805': 'P',
 '0806': 'S',
 '0808': 'S',
 '0809': 'S',
 '0811': 'S',
 '0813': 'P',
 '0815': 'S',
 '0816': 'S',
 '0817': 'P',
 '0818': 'S',
 '0819': 'S',
 '0820': 'S',
 '0822': 'S',
 '0823': 'S',
 '0824': 'S',
 '0825': 'P',
 '0828': 'S',
 '0829': 'P',
 '0830': 'P',
 '0834': 'P',
 '0835': 'S',
 '0836': 'S',
 '0839': 'S',
 '0840': 'P',
 '0845': 'S',
 '0846': 'S',
 '0848': 'P',
 '0849': 'S',
 '0850': 'S',
 '0851': 'P',
 '0853': 'S',
 '0859': 'S',
 '0860': 'P',
 '0863': 'S',
 '0865': 'S',
 '0867': 'S',
 '0868': 'S',
 '0869': 'S',
 '0870': 'P',
 '0871': 'S',
 '0873': 'P',
 '0874': 'S',
 '0875': 'S',
 '0876': 'S',
 '0877': 'P',
 '0878': 'S',
 '0881': 'S',
 '0883': 'P',
 '0885': 'S',
 '0889': 'P',
 '0890': 'P',
 '0893': 'P',
 '0898': 'S',
 '0899': 'P',
 '0901': 'S',
 '0902': 'P',
 '0903': 'S',
 '0904': 'P',
 '0905': 'P',
 '0906': 'S',
 '0907': 'P',
 '0910': 'S',
 '0911': 'P',
 '0912': 'S',
 '0913': 'P',
 '0915': 'S',
 '0918': 'S',
 '0919': 'P',
 '0921': 'S',
 '0922': 'P',
 '0923': 'S',
 '0924': 'S',
 '0925': 'P',
 '0926': 'S',
 '0927': 'S',
 '0928': 'P',
 '0930': 'P',
 '0931': 'P',
 '0933': 'P',
 '0935': 'P',
 '0938': 'S',
 '0939': 'P',
 '0940': 'P',
 '0941': 'P',
 '0942': 'P',
 '0944': 'P',
 '0946': 'P',
 '0947': 'P',
 '0949': 'P',
 '0951': 'S',
 '0952': 'S',
 '0953': 'P',
 '0955': 'S',
 '0956': 'S',
 '0957': 'P',
 '0960': 'S',
 '0961': 'P',
 '0964': 'P',
 '0965': 'S',
 '0966': 'S',
 '0968': 'P',
 '0969': 'P',
 '0970': 'P',
 '0971': 'P',
 '0972': 'P',
 '0975': 'P',
 '0976': 'S',
 '0978': 'P',
 '0979': 'S',
 '0982': 'P',
 '0983': 'S',
 '0984': 'S',
 '0985': 'P',
 '0987': 'P',
 '0988': 'S',
 '0989': 'P',
 '0990': 'S',
 '0991': 'S',
 '0992': 'S',
 '0993': 'S',
 '0994': 'S',
 '0995': 'P',
 '0997': 'S',
 '0998': 'P',
 '1000': 'P',
 '1001': 'S',
 '1002': 'S',
 '1004': 'S',
 '1005': 'S',
 '1006': 'S',
 '1008': 'S',
 '1011': 'P',
 '1012': 'P',
 '1013': 'S',
 '1014': 'P',
 '1015': 'S',
 '1017': 'S',
 '1018': 'P',
 '1019': 'S',
 '1020': 'P',
 '1024': 'P',
 '1025': 'P',
 '1026': 'S',
 '1027': 'P',
 '1029': 'P',
 '1030': 'P',
 '1031': 'S',
 '1032': 'P',
 '1033': 'P',
 '1034': 'P',
 '1035': 'P',
 '1036': 'S',
 '1038': 'S',
 '1040': 'S',
 '1043': 'P',
 '1045': 'P',
 '1046': 'S',
 '1047': 'P',
 '1048': 'P',
 '1049': 'P',
 '1051': 'S',
 '1052': 'S',
 '1053': 'S',
 '1054': 'S',
 '1056': 'P',
 '1057': 'P',
 '1058': 'S',
 '1060': 'S',
 '1062': 'P',
 '1063': 'P',
 '1065': 'S',
 '1066': 'P',
 '1068': 'S',
 '1071': 'P',
 '1075': 'S',
 '1076': 'P',
 '1077': 'P',
 '1078': 'P',
 '1079': 'P',
 '1080': 'S',
 '1082': 'S',
 '1083': 'S',
 '1084': 'S',
 '1085': 'P',
 '1086': 'P',
 '1088': 'S',
 '1089': 'P',
 '1091': 'P',
 '1093': 'P',
 '1094': 'P',
 '1096': 'S',
 '1097': 'S',
 '1099': 'P',
 '1100': 'P',
 '1102': 'P',
 '1105': 'S',
 '1108': 'S',
 '1110': 'S',
 '1112': 'P',
 '1113': 'S',
 '1114': 'S',
 '1115': 'S',
 '1116': 'S',
 '1117': 'P',
 '1121': 'P',
 '1123': 'P',
 '1127': 'S',
 '1129': 'S',
 '1130': 'S',
 '1133': 'P',
 '1136': 'S',
 '1140': 'S',
 '1141': 'S',
 '1142': 'P',
 '1144': 'S',
 '1146': 'P',
 '1147': 'P',
 '1148': 'P',
 '1149': 'S',
 '1150': 'S',
 '1152': 'S',
 '1153': 'P',
 '1154': 'P',
 '1155': 'P',
 '1156': 'S',
 '1161': 'S',
 '1162': 'S',
 '1163': 'P',
 '1165': 'P',
 '1166': 'P',
 '1167': 'P',
 '1168': 'P',
 '1169': 'S',
 '1170': 'S',
 '1173': 'S',
 '1174': 'P',
 '1175': 'S',
 '1177': 'P',
 '1178': 'S',
 '1179': 'S',
 '1180': 'S',
 '1182': 'P',
 '1185': 'P',
 '1186': 'S',
 '1187': 'S',
 '1188': 'P',
 '1190': 'P',
 '1191': 'S',
 '1192': 'P',
 '1193': 'S',
 '1195': 'P',
 '1197': 'P',
 '1199': 'P',
 '1203': 'S',
 '1206': 'P',
 '1208': 'P',
 '1210': 'P',
 '1211': 'S',
 '1212': 'P',
 '1213': 'P',
 '1214': 'P',
 '1215': 'S',
 '1216': 'P',
 '1218': 'P',
 '1220': 'P',
 '1221': 'S',
 '1222': 'P',
 '1223': 'S',
 '1225': 'P',
 '1228': 'S',
 '1229': 'P',
 '1230': 'S',
 '1231': 'P',
 '1232': 'S',
 '1233': 'P',
 '1234': 'S',
 '1235': 'S',
 '1236': 'P',
 '1238': 'S',
 '1239': 'P',
 '1240': 'S',
 '1242': 'P',
 '1243': 'P',
 '1246': 'P',
 '1248': 'S',
 '1250': 'S',
 '1254': 'S',
 '1255': 'S',
 '1256': 'S',
 '1258': 'P',
 '1259': 'S',
 '1260': 'P',
 '1261': 'P',
 '1263': 'S',
 '1264': 'P',
 '1267': 'S',
 '1269': 'P',
 '1271': 'P',
 '1273': 'S',
 '1274': 'P',
 '1278': 'P',
 '1279': 'P',
 '1280': 'P',
 '1281': 'S',
 '1282': 'P',
 '1283': 'S',
 '1284': 'S',
 '1285': 'P',
 '1286': 'S',
 '1287': 'P',
 '1288': 'P',
 '1289': 'S',
 '1291': 'P',
 '1292': 'S',
 '1293': 'P',
 '1294': 'S',
 '1299': 'S',
 '1300': 'S',
 '1302': 'S',
 '1304': 'P',
 '1306': 'S',
 '1307': 'P',
 '1308': 'S',
 '1309': 'P',
 '1310': 'S',
 '1311': 'P',
 '1312': 'P',
 '1316': 'S',
 '1317': 'P',
 '1322': 'P',
 '1323': 'P',
 '1324': 'S',
 '1325': 'S',
 '1326': 'S',
 '1328': 'P',
 '1330': 'S',
 '1331': 'S',
 '1332': 'S',
 '1333': 'P',
 '1335': 'P',
 '1336': 'S',
 '1337': 'S',
 '1340': 'S',
 '1342': 'P',
 '1345': 'S',
 '1347': 'P',
 '1348': 'S',
 '1350': 'S',
 '1351': 'P',
 '1352': 'P',
 '1353': 'S',
 '1355': 'P',
 '1356': 'S',
 '1357': 'S',
 '1360': 'S',
 '1362': 'S',
 '1365': 'S',
 '1366': 'P',
 '1368': 'P',
 '1370': 'S',
 '1371': 'P',
 '1375': 'S',
 '1376': 'P',
 '1377': 'P',
 '1378': 'P',
 '1379': 'S',
 '1380': 'S',
 '1381': 'S',
 '1382': 'S',
 '1383': 'S',
 '1384': 'S',
 '1385': 'P',
 '1386': 'P',
 '1387': 'P',
 '1389': 'S',
 '1390': 'P',
 '1391': 'P',
 '1393': 'S',
 '1395': 'S',
 '1397': 'S',
 '1398': 'P',
 '1399': 'S',
 '1400': 'P',
 '1401': 'P',
 '1402': 'S',
 '1403': 'P',
 '1404': 'S',
 '1406': 'S',
 '1407': 'P',
 '1408': 'S',
 '1410': 'P',
 '1412': 'S',
 '1413': 'S',
 '1414': 'P',
 '1415': 'P',
 '1416': 'P',
 '1417': 'S',
 '1419': 'S',
 '1420': 'S',
 '1421': 'S',
 '1423': 'S',
 '1424': 'P',
 '1425': 'P',
 '1426': 'P',
 '1427': 'S',
 '1428': 'S',
 '1430': 'P',
 '1431': 'P',
 '1433': 'S',
 '1434': 'P',
 '1435': 'P',
 '1438': 'P',
 '1439': 'S',
 '1440': 'S',
 '1442': 'S',
 '1443': 'P',
 '1444': 'S',
 '1445': 'S',
 '1447': 'P',
 '1450': 'S',
 '1451': 'S',
 '1452': 'P',
 '1453': 'P',
 '1454': 'S',
 '1455': 'S',
 '1457': 'S',
 '1458': 'S',
 '1460': 'P',
 '1461': 'S',
 '1462': 'P',
 '1463': 'S',
 '1465': 'P',
 '1467': 'S',
 '1474': 'P',
 '1478': 'P',
 '1479': 'P',
 '1481': 'P',
 '1484': 'P',
 '1485': 'P',
 '1488': 'P',
 '1489': 'S',
 '1490': 'P',
 '1491': 'P',
 '1493': 'S',
 '1498': 'P',
 '1499': 'S',
 '1500': 'S',
 '1501': 'P',
 '1503': 'P',
 '1506': 'P',
 '1507': 'S',
 '1509': 'P',
 '1510': 'S',
 '1511': 'S',
 '1515': 'S',
 '1520': 'S',
 '1521': 'S',
 '1523': 'S',
 '1524': 'S',
 '1525': 'P',
 '1526': 'P',
 '1527': 'P',
 '1528': 'P',
 '1529': 'S',
 '1531': 'S',
 '1532': 'S',
 '1533': 'P',
 '1536': 'S',
 '1539': 'S',
 '1540': 'P',
 '1541': 'S',
 '1542': 'S',
 '1543': 'P',
 '1544': 'P',
 ...}

In [88]:
df['side'].fillna(df['GroupId'].map(side_map), inplace = True)

In [90]:
df[df['side'].isnull()]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId,lastName,deck,side
15,0012_01,Earth,False,NaN,TRAPPIST-1e,31.0,False,32.0,0.0,876.0,0.0,0.0,Justie Pooles,False,0012,Pooles,G,NaN
93,0101_01,Mars,True,NaN,TRAPPIST-1e,31.0,False,0.0,0.0,0.0,0.0,0.0,Book Trad,True,0101,Trad,F,NaN
222,0239_01,Mars,False,NaN,TRAPPIST-1e,37.0,False,637.0,0.0,0.0,92.0,319.0,Diedow Resty,False,0239,Resty,F,NaN
272,0301_01,Earth,True,NaN,TRAPPIST-1e,16.0,False,0.0,0.0,0.0,0.0,0.0,Margia Wriggins,False,0301,Wriggins,G,NaN
280,0310_01,Europa,False,NaN,TRAPPIST-1e,67.0,False,0.0,230.0,0.0,4476.0,241.0,Naviton Coudered,False,0310,Coudered,B,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,8375_01,Earth,False,NaN,PSO J318.5-22,15.0,False,64.0,0.0,0.0,0.0,640.0,Carlen Valezaley,True,8375,Valezaley,G,NaN
7899,8437_01,Earth,False,NaN,PSO J318.5-22,36.0,False,52.0,0.0,132.0,334.0,176.0,Anny Tersony,False,8437,Tersony,G,NaN
8039,8603_01,Earth,True,NaN,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Hilip Klinson,False,8603,Klinson,G,NaN
8066,8623_01,Earth,False,NaN,TRAPPIST-1e,15.0,False,9.0,731.0,85.0,0.0,537.0,Vandy Hoffergess,False,8623,Hoffergess,G,NaN
8656,9233_01,Earth,False,NaN,TRAPPIST-1e,41.0,False,3.0,0.0,668.0,0.0,0.0,Royce Giller,True,9233,Giller,G,NaN

In [92]:
df['side'].fillna('S', inplace=True)

In [93]:
df.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            200
Transported       0
GroupId           0
lastName        200
deck              0
side              0
fee               0
dtype: int64

## Destination

In [97]:
dest_group = df.groupby(['GroupId','Destination']).size().reset_index()

In [98]:
dest_group = dest_group.sort_values(0, ascending=False)

In [100]:
dest_group = dest_group.drop_duplicates() # keep = First 중복을 제거하면서, 제일 위에꺼만 남김

In [102]:
dest_map = {}
for g, d in zip(dest_group['GroupId'], dest_group['Destination']) :
    dest_map[g] = d

In [103]:
df['Destination'].fillna(df['GroupId'].map(dest_map), inplace=True)

In [104]:
df['Destination'].isnull().sum()

103

In [105]:
df['Destination'].fillna('TRAPPIST-1e', inplace=True)

In [107]:
df.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination       0
Age             179
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            200
Transported       0
GroupId           0
lastName        200
deck              0
side              0
fee               0
dtype: int64

## CryoSleep Null 처리

In [110]:
df[df['CryoSleep'] == True]['fee'].mean() # 자는애들은 돈 못써~

0.0

In [111]:
import numpy as np

In [112]:
df['CryoSleep'] = np.where(df['fee'] > 0 , False, True)

In [113]:
df['CryoSleep'].isnull().sum()

0

## Age Null

In [117]:
df.groupby('Transported')['Age'].mean() #큰차이가 없넹

Transported
False    29.922858
True     27.748834
Name: Age, dtype: float64

In [118]:
df.groupby('Transported')['Age'].median() #큰차이가 없넹

Transported
False    27.0
True     26.0
Name: Age, dtype: float64

In [119]:
df['Age'].fillna(df['Age'].median(), inplace=True)

In [120]:
df.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep         0
Cabin           199
Destination       0
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            200
Transported       0
GroupId           0
lastName        200
deck              0
side              0
fee               0
dtype: int64

In [121]:
del_col = ['PassengerId','Cabin','Name','lastName']

In [122]:
df.drop(del_col, axis = 1, inplace=True)

In [123]:
df.isnull().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
GroupId         0
deck            0
side            0
fee             0
dtype: int64

# Label Encorder 쓰자!

In [127]:
from sklearn.preprocessing import LabelEncoder

In [145]:
df.dtypes

HomePlanet        int32
CryoSleep         int64
Destination       int32
Age             float64
VIP               int64
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Transported       int64
GroupId           int32
deck              int32
side              int32
fee             float64
dtype: object

In [124]:
df

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,GroupId,deck,side,fee
0,Europa,True,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0001,B,P,0.0
1,Earth,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,0002,F,S,736.0
2,Europa,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0003,A,S,10383.0
3,Europa,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0003,A,S,5176.0
4,Earth,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,0004,F,S,1091.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,9276,A,P,8536.0
8689,Earth,True,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False,9278,G,S,0.0
8690,Earth,False,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,9279,G,S,1873.0
8691,Europa,False,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,9280,E,S,4637.0
8692,Europa,False,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,9280,E,S,4826.0

In [125]:
obj_col = []
for i,j in zip(df.dtypes.index, df.dtypes.values) :
    if j == 'object' :
        obj_col.append(i)

In [129]:
obj_col

['HomePlanet', 'Destination', 'GroupId', 'deck', 'side']

In [135]:
bool_col = []
for i,j in zip(df.dtypes.index, df.dtypes.values) :
    if j == 'bool' :
        bool_col.append(i)

In [136]:
bool_col # 굳이 안해도 됨

['CryoSleep', 'VIP', 'Transported']

In [137]:
label_col = obj_col + bool_col  # 굳이 안해도 됨

In [128]:
label = LabelEncoder()

In [138]:
for col in label_col :
    label = LabelEncoder()
    df[col] = label.fit_transform(df[col])

In [139]:
df

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,GroupId,deck,side,fee
0,1,1,2,39.0,0,0.0,0.0,0.0,0.0,0.0,0,0,1,0,0.0
1,0,0,2,24.0,0,109.0,9.0,25.0,549.0,44.0,1,1,5,1,736.0
2,1,0,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0,2,0,1,10383.0
3,1,0,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0,2,0,1,5176.0
4,0,0,2,16.0,0,303.0,70.0,151.0,565.0,2.0,1,3,5,1,1091.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,1,0,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0,6213,0,0,8536.0
8689,0,1,1,18.0,0,0.0,0.0,0.0,0.0,0.0,0,6214,6,1,0.0
8690,0,0,2,26.0,0,0.0,0.0,1872.0,1.0,0.0,1,6215,6,1,1873.0
8691,1,0,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0,6216,4,1,4637.0
8692,1,0,2,44.0,0,126.0,4688.0,0.0,0.0,12.0,1,6216,4,1,4826.0

In [143]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [141]:
X = df.drop(['Transported','GroupId'], axis = 1)
Y = df['Transported']

In [146]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=1)

In [148]:
rfc = RandomForestClassifier()

In [149]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [150]:
rfc.score(x_train, y_train)

0.9400345125107852

In [153]:
rfc.score(x_test, y_test)

0.7837837837837838

In [154]:
import pickle

In [ ]:
with open('rfc.

In [144]:
model1 = RandomForestClassifier()
model2 = AdaBoostClassifier()
model3 = GradientBoostingClassifier()

In [ ]:
model_list = [('RandomForest', model1), ('AdaBoostClassifie', model2), ('GradientBoosting', model3)]

In [35]:
for name, model in model_list :
    model.fit(x_train, y_train)
    score = model.score(x_test, y_test)
    print(name, score)

DT 0.896875
LR 0.9
SVC 0.903125

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [32]:
vc_model.fit(x_train, y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

VotingClassifier(estimators=[('DT', DecisionTreeClassifier()),
                             ('LR', LogisticRegression()), ('SVC', SVC())])